apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:ZFV2CyFw/k3K1EhUvkO3GpzydqKtJAmolaRiyHq2/2HHjBwIyxqZJ/v/U5AHd9XepZWlkkwOVCSooYPCGnO7cyPqNg7R3P8Q,iv:2qquRwkglUueTKCCIcfnhyv3jWXaRf4UseYebGJD0W0=,tag:TgCTlV1lxrEp9IjuUAUKoA==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSGttNEpBM1FSOGREbVh0
            ejNsM0xKUnFLZHcrM3FQNzMxUHVQTkl2UnpNCnZvQzVhMDhBUWV1eEFWN3JXMXVW
            TzZvRU9MamtYRjhuZ0ZUMldFY3pDM3cKLS0tIEo3R3d3akxVVkwzQTVpQlUrQ2tL
            VkpRZ04rWlUwTDNUNnJqOHpYVk1kem8KXP4lMA8uXQIVRmAm08ol/rLPWGM/2lU9
            k9Su53ddwtG3GuTyPXfuQuFqoSu3cbv5H6mFOahGrmYdixcm8u7BwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:20:52Z"
    mac: ENC[AES256_GCM,data:9WO0+cBi7CzGow9hFB/hY88phx+rTb2S9S5guah3ahoneVvd4NNP4LW7Hn7KY9A8Y+VSkkAtsRE1YzmSs9mUcpJKhdf1ORv93CLDOrTptrM/3ZJzqN8ZKjsA8lir6nQ0BARRIVARuTlCf3j9rpc5oWMDMtd7N/dihwpcWrAykYI=,iv:A5agNGR0Ilh3O33T7e+vD1QD2TO0JgjaxkLRHhbnRYg=,tag:jv3KQ6Zw9mf9EalxjQSH8g==,type:str]
    version: 3.13.1
