apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QRKSAlWGLZpO2qxkIN+VdGfnI6NjQ+4qZ8Obazh3Ez/IIw+VRrtY+b2sZSo=,iv:YFot8+f+ViCZmO9LpFNwCkqs0TPkgpqM0QAjZDudF8U=,tag:HdnE1Mn1GZ2MLLPQ0Mbuhw==,type:str]
kind: Secret
metadata:
    name: statecraft-postgres
    namespace: statecraft-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVVJyVHEvQWJkeG1yNlEv
            MUVTNGd5cDF3RVJ5NnFFSkh3aFM4a0svcW5BClRsN09iLytEdE9CV2t2UjdVY3NO
            RzlRNmovYXMvTTJ6ZHJIMlAvL3hIcVUKLS0tIEN5Ym9wQUtTbWlqQjh1d2ZwaWJC
            c29qVDRueU5mZHhqTDgrMU9Ld1dWbmsKhxBgH5EEo7ieSxiREm/7KICX0TkYFW/s
            du3Q3rcoowhjEUrkv9biGCO9gbiLX6nbJO9jLbd6ZI0qGRukJeh7EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:20:52Z"
    mac: ENC[AES256_GCM,data:nBvSOftU0Qd6eCikCeK5hCO0gyEDZ/3QUP6/fO1hb1OBPqL2FacX99dw7tjg+O57cQ+Es4d2m2kpsLbVzb1Q3PJmOsprtsR6BMbjTI9gy8IeO+M6kMDu6xslMXxUmp+KNS59pot93GgKAuB61QIwB0z8NXjXjyve12cCtf2r8CU=,iv:Sbf3kbERl5LwQTewyFElqEhwodN3KORDjGRlklm48pM=,tag:P3OjQpZAmAjlYvYXS5rjMg==,type:str]
    version: 3.13.1
