apiVersion: v1
kind: Secret
metadata:
    name: statecraft-platform-backup
    namespace: statecraft-system
    labels:
        statecraft.spec: 009-control-plane-deploy
type: Opaque
stringData:
    PLATFORM_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:lAfXYuDwa/MNMZ1NcvClS3hPXBM=,iv:oq6jKw4pl/kAnlDjWwJ9Tw51ROOtMY9AVyBstQmrN+g=,tag:yJvNEzinuYz7okivZE+I/Q==,type:str]
    PLATFORM_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/Q5KsSE+YPR2mW9iAU0yFCU1jB2fydFMknJddkjvbS6IaWDrm8kh/Q==,iv:WJPmLn23MIOwJNR6d7zpQEFfh66ewDSFH/z/F4VWTlM=,tag:P0RbRke7JKxGHVIW6IWlNA==,type:str]
    PLATFORM_S3_RESTIC_PASSWORD: ENC[AES256_GCM,data:tUeMtAjcXqlg32KIbLLdhPAQhzGXbTvuOAx0AjO9WQg7LdxoaUjzXl7DScY=,iv:nheW4idMHmX4g2EA9fQrPBmmtufsScdTv6qNLAw4r2E=,tag:JyOZ81yGpZwr9DJKIRnZOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL2pycG1uRGtNRzd3K1F2
            SU1iS0tML3FXQi8yR1pXZ3V2ZlF5Z0ZlOURjCkh6dXJENytUUTRrVXJqbU02a3hp
            MGJOU0duNFdJU3BkVnA4TjFQOVowMXcKLS0tIDZBSUpVaHJyQlp4Si9ZbkhxTldJ
            NUxUSnJ5b1pFQlhtaFRSUUVSSUYzS1EK5i2osmBvdrV/CzDvEPL6LZFt9qnzZp8C
            BLPNnv0nnp3ZNW3tuDgkXvlIo2TbfExjixdeQzBsAGjV/h2uoSQf/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T00:41:53Z"
    mac: ENC[AES256_GCM,data:qoWKvHfwCuJTIyosncfCczLkTpAmtxTQ0g1qPXv7LK7wPr+OsZ6nEMWtOisle2SQLpJaZSE926rr0AVbkTYY4Ynsx6hvk14SlSNvaqyljGOIYcJn/2n60lYs4C21k87HmVP53SJf93wjOJiAsHCgxFpyOj9guasqFGb7D9Betdg=,iv:xqe3ryD5fKgndXKzwgx4QYIU2qOKIDSuecycEqvMLk0=,tag:1KOVaVUQhN6XcUx0Y1lWOQ==,type:str]
    version: 3.13.1
