//! tauri-specta bindings — auto-generates TypeScript types from Rust command signatures.
//!
//! ## How it works
//! 1. New commands are annotated with `#[specta::specta]` in addition to `#[tauri::command]`.
//! 2. They are added to `collect_commands![]` below AND to `generate_handler![]` in `lib.rs`.
//! 3. In debug builds `export_ts_bindings()` regenerates `src/lib/bindings.ts` on every
//!    app start, so the frontend always has up-to-date types.
//!
//! ## Adding a command
//! ```text
//! // In your commands file:
//! #[tauri::command]
//! #[specta::specta]
//! pub fn my_command(arg: MyType) -> Result<MyReturn, MyError> { ... }
//!
//! // In bindings.rs collect_commands![]:
//! my_module::my_command,
//!
//! // In lib.rs generate_handler![]:
//! my_module::my_command,
//! ```

use specta_typescript::BigIntExportBehavior;
use tauri_specta::{Builder, collect_commands};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Recovery system
        crate::commands::recovery::save_emergency_data,
        crate::commands::recovery::load_emergency_data,
        crate::commands::recovery::cleanup_old_recovery_files,
        // Updater with SHA-256 verification
        crate::commands::updater::check_for_update,
        crate::commands::updater::download_and_install_update,
        // Native git operations
        crate::commands::git::git_diff,
        crate::commands::git::git_status,
        crate::commands::git::git_ahead_behind,
        crate::commands::git::git_current_branch,
        crate::commands::git::git_last_commit,
        // Quick pane window
        crate::commands::quick_pane::show_quick_pane,
        crate::commands::quick_pane::dismiss_quick_pane,
        crate::commands::quick_pane::toggle_quick_pane,
        crate::commands::quick_pane::get_default_quick_pane_shortcut,
        crate::commands::quick_pane::update_quick_pane_shortcut,
        crate::commands::quick_pane::set_quick_pane_enabled,
        // Window control (zoom, progress bar, bounds, WSL)
        crate::commands::window_ctrl::set_zoom,
        crate::commands::window_ctrl::get_zoom,
        crate::commands::window_ctrl::broadcast_zoom,
        crate::commands::window_ctrl::set_progress_bar,
        crate::commands::window_ctrl::get_window_bounds,
        crate::commands::window_ctrl::set_window_bounds,
        crate::commands::window_ctrl::is_wsl,
        // WSL distro listing and execution
        crate::commands::wsl::wsl_is_available,
        crate::commands::wsl::wsl_list_distros,
        crate::commands::wsl::wsl_execute,
        // Sandbox status
        crate::commands::sandbox::sandbox_status,
        // Sidecar port discovery + spec 183 boot-gate observability
        crate::sidecars::get_sidecar_ports,
        crate::sidecars::check_axiomregent_alive,
        crate::sidecars::boot_gate_status,
        crate::sidecars::quit_opc,
        // Preflight / governance reference
        crate::commands::analysis::get_preflight_safety_tier_reference,
        crate::commands::analysis::get_tool_tier_assignments,
        // OS keychain (spec 087 Phase 5)
        crate::commands::keychain::keychain_store,
        crate::commands::keychain::keychain_retrieve,
        crate::commands::keychain::keychain_clear,
        // Project clone tokens (spec 112 §6.4.4)
        crate::commands::keychain::clone_token_store,
        crate::commands::keychain::clone_token_load,
        crate::commands::keychain::clone_token_clear,
        // Desktop OAuth (spec 080 Phase 1)
        crate::commands::auth::auth_start_login,
        crate::commands::auth::auth_handle_callback,
        crate::commands::auth::auth_select_org,
        crate::commands::auth::auth_switch_org,
        crate::commands::auth::auth_refresh_token,
        crate::commands::auth::auth_get_status,
        crate::commands::auth::auth_logout,
        crate::commands::auth::auth_take_pending_callback,
        // App settings (runtime-configurable Statecraft URL)
        crate::commands::settings::get_statecraft_base_url,
        crate::commands::settings::set_statecraft_base_url,
        crate::commands::settings::reconnect_statecraft_duplex,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Called automatically in debug builds on every app start.
/// Run manually: `cargo test export_bindings -- --ignored`
pub fn export_ts_bindings() {
    let out_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/bindings.ts");
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .bigint(BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            out_path,
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerate `src/lib/bindings.ts`.
    /// Run with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
