// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Bartek Kus
// Spec: specs/121-claim-provenance-enforcement/spec.md — FR-010, FR-032, FR-033

//! Emitters for the Phase-5 cascade artifacts:
//!
//! * `emit_assumption_manifest` writes `assumption-only-manifest.md`
//!   (FR-010). Regenerated from scratch on every call so the manifest
//!   matches the latest validator run; operator hand-edits are not
//!   expected.
//!
//! * `append_pending_promotion` adds one record to `pending-promotion.md`
//!   (FR-032). Stage 4 / Stage 5 call this every time they skip
//!   emission for an Assumption-tagged claim.
//!
//! * `parse_assumption_manifest` reads the manifest back into structured
//!   `AssumptionManifestEntry`s for the cascade check.
//!
//! Manifest output is byte-deterministic for the same inputs (FR-002):
//! claims are sorted by `claim_id`, and within each claim
//! `extractedEntityCandidates` is already alphabetised by Phase 2's
//! `detect_external_entities`.

use crate::ValidationReport;
use factory_contracts::provenance::{
    AnchorHash, AssumptionManifestEntry, Claim, ClaimId,
    PendingPromotionEntry, ProvenanceMode,
};
#[cfg(test)]
use factory_contracts::provenance::ClaimKind;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// Compose the markdown body of `assumption-only-manifest.md`. Useful
/// for callers that want to inspect or test the body without writing to
/// disk; `emit_assumption_manifest` writes the same body to a file.
pub fn assumption_manifest_body(
    report: &ValidationReport,
    claims: &[Claim],
) -> String {
    // Index claims by id for O(1) lookup of assumption tags + candidates.
    let by_id: BTreeMap<&ClaimId, &Claim> =
        claims.iter().map(|c| (&c.id, c)).collect();

    // Walk the report records (already in input order) and collect those
    // whose final mode is Assumption / AssumptionOrphaned.
    let mut entries: Vec<AssumptionManifestEntry> = Vec::new();
    for r in &report.claims {
        let is_assumption = matches!(
            r.provenance_mode,
            ProvenanceMode::Assumption | ProvenanceMode::AssumptionOrphaned
        );
        if !is_assumption {
            continue;
        }
        // Resolve the AssumptionTag fields. Three cases:
        //   1. Matching Claim with Some(tag) → use the operator-supplied
        //      owner / rationale / expiresAt.
        //   2. Matching Claim with None on assumption (orphan after drift)
        //      OR no matching Claim → synthesise a placeholder so the
        //      manifest entry is still well-shaped. Operators see the
        //      "orphaned" marker and know the row needs human attention.
        let claim_opt = by_id.get(&r.id).copied();
        let (owner, rationale, expires_at) = match claim_opt
            .and_then(|c| c.assumption.as_ref().map(|t| (c, t)))
        {
            Some((_, tag)) => (
                tag.owner.clone(),
                tag.rationale.clone(),
                tag.expires_at,
            ),
            None => (
                "(unknown — orphaned)".to_string(),
                "citation drift; original quote no longer in corpus"
                    .to_string(),
                // FR-002 byte-determinism: when neither the report record
                // nor the claims slice carries a real timestamp, use the
                // Unix epoch as a stable sentinel rather than wall clock.
                // Operators see `1970-01-01T00:00:00Z` and know the row
                // needs a real expiry written by the next run.
                claim_opt.map(|c| c.minted_at).unwrap_or_else(|| {
                    chrono_epoch_zero()
                }),
            ),
        };
        entries.push(AssumptionManifestEntry {
            id: r.id.clone(),
            kind: r.kind,
            anchor_hash: r.anchor_hash.clone(),
            owner,
            rationale,
            expires_at,
            extracted_entity_candidates: r.extracted_entity_candidates.clone(),
            pending_promotion_path: "pending-promotion.md".into(),
        });
    }

    // Sort by claim id for byte-determinism (FR-002).
    entries.sort_by(|a, b| a.id.cmp(&b.id));

    let mut out = String::new();
    let _ = writeln!(out, "# Assumption-Only Manifest");
    let _ = writeln!(
        out,
        "<!-- generated by provenance-validator; do not edit manually -->"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Schema: spec 121 (claim-provenance-enforcement) FR-010, FR-032."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "**Count:** {}", entries.len());
    let _ = writeln!(out);
    if entries.is_empty() {
        let _ = writeln!(
            out,
            "_No `Assumption` or `AssumptionOrphaned` claims in the latest validator run._",
        );
        return out;
    }
    for e in &entries {
        let _ = writeln!(out, "## {}", e.id);
        let _ = writeln!(out);
        let _ = writeln!(out, "- **id**: `{}`", e.id);
        let _ = writeln!(out, "- **kind**: `{}`", e.kind.prefix());
        let _ = writeln!(out, "- **anchorHash**: `{}`", e.anchor_hash);
        let _ = writeln!(out, "- **owner**: {}", e.owner);
        let _ = writeln!(out, "- **rationale**: {}", e.rationale);
        let _ = writeln!(
            out,
            "- **expiresAt**: {}",
            e.expires_at.format("%Y-%m-%dT%H:%M:%SZ")
        );
        if e.extracted_entity_candidates.is_empty() {
            let _ = writeln!(out, "- **extractedEntityCandidates**: _none_");
        } else {
            let _ = writeln!(
                out,
                "- **extractedEntityCandidates**: {}",
                e.extracted_entity_candidates
                    .iter()
                    .map(|s| format!("`{s}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let _ = writeln!(
            out,
            "- **pendingPromotionPath**: `{}`",
            e.pending_promotion_path
        );
        let _ = writeln!(out);
    }
    out
}

/// Emit `assumption-only-manifest.md` in `dest_dir`. Overwrites any
/// existing file (the manifest is regenerated from scratch every run).
pub fn emit_assumption_manifest(
    report: &ValidationReport,
    claims: &[Claim],
    dest_dir: &Path,
) -> std::io::Result<()> {
    std::fs::create_dir_all(dest_dir)?;
    let path = dest_dir.join("assumption-only-manifest.md");
    std::fs::write(path, assumption_manifest_body(report, claims))
}

/// Append one `PendingPromotionEntry` to `pending-promotion.md` in
/// `dest_dir`. Creates the file with a header on first call; subsequent
/// calls append at the end.
///
/// NOTE on concurrency: Stage 4 and Stage 5 are dispatched sequentially
/// in the current factory-engine. If a future spec parallelises stages,
/// this append must be guarded by a file lock — surface that change as
/// part of that future work.
pub fn append_pending_promotion(
    entry: &PendingPromotionEntry,
    dest_dir: &Path,
) -> std::io::Result<()> {
    use std::fs::OpenOptions;
    use std::io::Write;
    std::fs::create_dir_all(dest_dir)?;
    let path = dest_dir.join("pending-promotion.md");
    let exists = path.exists();
    let mut f = OpenOptions::new().create(true).append(true).open(&path)?;
    if !exists {
        writeln!(
            f,
            "# Pending Promotion Manifest\n<!-- generated by provenance-validator; appended each run -->\n\nSchema: spec 121 FR-032.\n"
        )?;
    }
    writeln!(f, "## {}", entry.claim_id)?;
    writeln!(f)?;
    writeln!(f, "- **claimId**: `{}`", entry.claim_id)?;
    writeln!(f, "- **anchorHash**: `{}`", entry.anchor_hash)?;
    writeln!(f, "- **kind**: `{}`", entry.kind.prefix())?;
    writeln!(f, "- **wouldEmit**:")?;
    if entry.would_emit.is_empty() {
        writeln!(f, "  - _no skipped artifacts recorded yet_")?;
    } else {
        for em in &entry.would_emit {
            writeln!(
                f,
                "  - stage {}: `{}` — {}",
                em.stage, em.artifact_kind, em.description,
            )?;
        }
    }
    writeln!(f)?;
    Ok(())
}

/// Parse `assumption-only-manifest.md` back into a list of
/// `AssumptionManifestEntry`s. Used by the cascade check to know which
/// surface forms to grep for.
///
/// V1 grammar: each `## <claim_id>` opens an entry; `**anchorHash**:`
/// and `**extractedEntityCandidates**:` lines populate the fields the
/// cascade check needs. Other fields are parsed best-effort. The parser
/// is deliberately tolerant — its job is to read what
/// `emit_assumption_manifest` wrote, NOT to be a general markdown
/// parser.
pub fn parse_assumption_manifest(
    body: &str,
) -> Vec<ParsedAssumptionEntry> {
    let mut out: Vec<ParsedAssumptionEntry> = Vec::new();
    let mut current: Option<ParsedAssumptionEntry> = None;
    for line in body.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("## ") {
            // close previous
            if let Some(e) = current.take()
                && !e.id.0.is_empty()
            {
                out.push(e);
            }
            current = Some(ParsedAssumptionEntry {
                id: ClaimId(rest.trim().to_string()),
                anchor_hash: AnchorHash(String::new()),
                surface_forms: Vec::new(),
            });
            continue;
        }
        let entry = match current.as_mut() {
            Some(e) => e,
            None => continue,
        };
        if let Some(rest) = trimmed.strip_prefix("- **anchorHash**:") {
            entry.anchor_hash =
                AnchorHash(strip_backticks(rest.trim()).to_string());
        } else if let Some(rest) =
            trimmed.strip_prefix("- **extractedEntityCandidates**:")
        {
            // Comma-separated list of `surface_form` tokens with backticks.
            let rest = rest.trim();
            if rest == "_none_" {
                continue;
            }
            for piece in rest.split(',') {
                let cleaned = strip_backticks(piece.trim()).to_string();
                if !cleaned.is_empty() {
                    entry.surface_forms.push(cleaned);
                }
            }
        }
    }
    if let Some(e) = current.take()
        && !e.id.0.is_empty()
    {
        out.push(e);
    }
    out
}

/// Cascade-check view over a parsed manifest entry — only the fields
/// the check needs are populated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedAssumptionEntry {
    pub id: ClaimId,
    pub anchor_hash: AnchorHash,
    pub surface_forms: Vec<String>,
}

fn strip_backticks(s: &str) -> &str {
    s.trim_start_matches('`').trim_end_matches('`')
}

/// FR-002 byte-determinism sentinel for the `expiresAt` field of an
/// orphaned manifest entry that has no upstream timestamp to inherit.
fn chrono_epoch_zero() -> factory_contracts::DateTime<factory_contracts::Utc> {
    use factory_contracts::TimeZone;
    factory_contracts::Utc.timestamp_opt(0, 0).unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{TimeZone, Utc};
    use factory_contracts::provenance::{
        anchor_hash, AssumptionTag, Citation, ProvenanceMode,
    };
    use std::path::PathBuf;

    fn now() -> chrono::DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 5, 1, 0, 0, 0).unwrap()
    }

    fn assumption_claim(
        id: &str,
        kind: ClaimKind,
        text: &str,
        owner: &str,
    ) -> Claim {
        Claim {
            id: ClaimId(id.into()),
            kind,
            stage: 1,
            minted_at: now(),
            text: text.into(),
            anchor_hash: anchor_hash(text),
            provenance_mode: ProvenanceMode::Derived,
            citations: vec![],
            assumption: Some(AssumptionTag {
                owner: owner.into(),
                rationale: "pending Globex Finance".into(),
                expires_at: Utc.with_ymd_and_hms(2026, 7, 30, 0, 0, 0).unwrap(),
                tagged_at: now(),
            }),
            names_external_entity: false,
            extracted_entity_candidates: vec![],
            candidate_promotion: None,
        }
    }

    fn report_with_one_assumption(
        id: &str,
        anchor: &str,
        candidates: Vec<String>,
    ) -> ValidationReport {
        ValidationReport {
            schema_version: "1.0.0".into(),
            provenance_schema_version: "1.0.0".into(),
            validator_version: "0.1.0".into(),
            extracted_corpus_hash: "0".repeat(64),
            allowlist_version_hash: "0".repeat(64),
            claims: vec![crate::ClaimRecord {
                id: ClaimId(id.into()),
                kind: ClaimKind::Int,
                anchor_hash: AnchorHash(anchor.into()),
                provenance_mode: ProvenanceMode::Assumption,
                names_external_entity: true,
                extracted_entity_candidates: candidates,
                entity_search: vec![],
            }],
            summary: crate::ValidationSummary {
                total: 1,
                derived_count: 0,
                derived_weak_count: 0,
                assumption_count: 1,
                assumption_orphaned_count: 0,
                rejected_count: 0,
                assumption_slots_consumed: 1,
            },
            panic_reason: None,
        }
    }

    // ---- assumption_manifest_body ----

    #[test]
    fn manifest_emits_required_fields() {
        let report = report_with_one_assumption(
            "INT-003",
            "abc123",
            vec!["Globex".into(), "Initech".into()],
        );
        let claim = assumption_claim(
            "INT-003",
            ClaimKind::Int,
            "Globex integration via Globex Finance",
            "Ops Lead",
        );
        let body = assumption_manifest_body(&report, &[claim]);
        assert!(body.contains("## INT-003"));
        assert!(body.contains("- **id**: `INT-003`"));
        assert!(body.contains("- **anchorHash**: `abc123`"));
        assert!(body.contains("- **kind**: `INT`"));
        assert!(body.contains("Ops Lead"));
        assert!(body.contains("`Globex`"));
        assert!(body.contains("`Initech`"));
        assert!(body.contains("pending-promotion.md"));
    }

    #[test]
    fn manifest_skips_non_assumption_claims() {
        let mut report = report_with_one_assumption(
            "INT-003",
            "abc",
            vec!["Globex".into()],
        );
        // change to Derived — manifest should be empty
        report.claims[0].provenance_mode = ProvenanceMode::Derived;
        let body = assumption_manifest_body(&report, &[]);
        assert!(body.contains("**Count:** 0"));
        assert!(body.contains("_No `Assumption`"));
    }

    #[test]
    fn manifest_is_byte_stable() {
        let report = report_with_one_assumption(
            "INT-003",
            "abc",
            vec!["Globex".into(), "Initech".into()],
        );
        let claim = assumption_claim(
            "INT-003",
            ClaimKind::Int,
            "Globex",
            "ops",
        );
        let b1 = assumption_manifest_body(&report, std::slice::from_ref(&claim));
        let b2 = assumption_manifest_body(&report, &[claim]);
        assert_eq!(b1, b2);
    }

    #[test]
    fn manifest_byte_stable_for_fully_orphaned_record() {
        // Regression for FR-002 determinism: when the report carries an
        // AssumptionOrphaned record but no matching Claim is supplied,
        // the synthetic owner / expiresAt must be byte-stable across
        // runs. Previously this called wall-clock `now_utc()`; now it
        // uses the Unix epoch sentinel.
        let mut report = report_with_one_assumption(
            "INT-003",
            "abc",
            vec!["Globex".into()],
        );
        report.claims[0].provenance_mode = ProvenanceMode::AssumptionOrphaned;
        let b1 = assumption_manifest_body(&report, &[]);
        std::thread::sleep(std::time::Duration::from_millis(2));
        let b2 = assumption_manifest_body(&report, &[]);
        assert_eq!(b1, b2);
        // Sentinel is the Unix epoch — operators see it as "needs real
        // expiry on next run".
        assert!(b1.contains("1970-01-01T00:00:00Z"));
    }

    #[test]
    fn manifest_writes_to_disk() {
        let dir = tempfile::tempdir().unwrap();
        let report = report_with_one_assumption(
            "INT-003",
            "abc",
            vec!["Globex".into()],
        );
        let claim = assumption_claim(
            "INT-003",
            ClaimKind::Int,
            "Globex",
            "ops",
        );
        emit_assumption_manifest(&report, &[claim], dir.path()).unwrap();
        let path = dir.path().join("assumption-only-manifest.md");
        assert!(path.exists());
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("INT-003"));
    }

    // ---- pending-promotion.md ----

    #[test]
    fn pending_promotion_creates_and_appends() {
        use factory_contracts::provenance::PendingEmission;
        let dir = tempfile::tempdir().unwrap();
        let entry = PendingPromotionEntry {
            claim_id: ClaimId("INT-003".into()),
            anchor_hash: AnchorHash("abc".into()),
            kind: ClaimKind::Int,
            would_emit: vec![PendingEmission {
                stage: 4,
                artifact_kind: "ddl_table".into(),
                description: "table payment_request (skipped)".into(),
            }],
        };
        append_pending_promotion(&entry, dir.path()).unwrap();
        let path = dir.path().join("pending-promotion.md");
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("# Pending Promotion Manifest"));
        assert!(body.contains("## INT-003"));
        assert!(body.contains("payment_request"));

        // Append a second entry — header is NOT written again.
        let second = PendingPromotionEntry {
            claim_id: ClaimId("INT-004".into()),
            anchor_hash: AnchorHash("def".into()),
            kind: ClaimKind::Int,
            would_emit: vec![],
        };
        append_pending_promotion(&second, dir.path()).unwrap();
        let body2 = std::fs::read_to_string(&path).unwrap();
        assert_eq!(body2.matches("# Pending Promotion Manifest").count(), 1);
        assert!(body2.contains("## INT-004"));
    }

    // ---- parse_assumption_manifest ----

    #[test]
    fn parser_round_trip() {
        let report = report_with_one_assumption(
            "INT-003",
            "anchor-abc",
            vec!["Globex".into(), "Initech".into(), "Globex Finance".into()],
        );
        let claim = assumption_claim(
            "INT-003",
            ClaimKind::Int,
            "Globex",
            "ops",
        );
        let body = assumption_manifest_body(&report, &[claim]);
        let parsed = parse_assumption_manifest(&body);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].id.0, "INT-003");
        assert_eq!(parsed[0].anchor_hash.0, "anchor-abc");
        assert!(parsed[0].surface_forms.contains(&"Globex".to_string()));
        assert!(parsed[0].surface_forms.contains(&"Initech".to_string()));
        assert!(parsed[0]
            .surface_forms
            .contains(&"Globex Finance".to_string()));
    }

    #[test]
    fn parser_handles_empty_manifest() {
        let body = "# Assumption-Only Manifest\n\n_None_\n";
        let parsed = parse_assumption_manifest(body);
        assert!(parsed.is_empty());
    }

    #[test]
    fn parser_handles_orphaned_with_synthetic_owner() {
        let mut report = report_with_one_assumption(
            "INT-003",
            "abc",
            vec!["Globex".into()],
        );
        report.claims[0].provenance_mode = ProvenanceMode::AssumptionOrphaned;
        // No Claim provided in `claims` slice — emitter should still
        // produce an entry with a synthetic owner string.
        let body = assumption_manifest_body(&report, &[]);
        assert!(body.contains("INT-003"));
        assert!(body.contains("orphaned"));
    }

    // ---- silence unused warnings for citation in PromotionAuditPayload tests ----

    #[allow(dead_code)]
    fn _suppress_citation_unused() -> Citation {
        Citation {
            source: PathBuf::from("a"),
            line_range: (1, 1),
            quote: "x".into(),
            quote_hash: factory_contracts::provenance::QuoteHash("h".into()),
        }
    }
}
