image:
  repository: statecraftdevacr.azurecr.io/statecraft

serviceAccount:
  annotations:
    azure.workload.identity/client-id: ""

podLabels:
  azure.workload.identity/use: "true"

secrets:
  provider: "eso"
  storeRef:
    name: azure-keyvault
    kind: ClusterSecretStore
