// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Saves emergency data to a JSON file for later recovery.
 * Uses an atomic write (temp file → rename) so a crash mid-write never corrupts existing data.
 * Enforces a 10 MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns `RecoveryError::FileNotFound` if the file does not exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days. Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks GitHub releases for a version newer than the running app.
 * 
 * Returns `UpdateError::NoUpdateAvailable` when already up to date.
 */
async checkForUpdate() : Promise<Result<UpdateInfo, UpdateError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads the installer from `url`, verifies its SHA-256 against `expected_checksum`,
 * then launches it and exits the app.
 * 
 * This command never returns `Ok(())` — it calls `std::process::exit(0)` on success.
 */
async downloadAndInstallUpdate(url: string, expectedChecksum: string) : Promise<Result<null, UpdateError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_and_install_update", { url, expectedChecksum }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the unified diff.
 * 
 * - `ref1 = None, ref2 = None` → HEAD vs working directory (includes staged)
 * - `ref1 = Some("HEAD~1"), ref2 = Some("HEAD")` → diff between two commits
 */
async gitDiff(repoPath: string, ref1: string | null, ref2: string | null) : Promise<Result<GitDiff, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { repoPath, ref1, ref2 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the working-tree status (tracked + untracked files).
 */
async gitStatus(repoPath: string) : Promise<Result<GitStatusEntry[], GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns how many commits the local branch is ahead of and behind its upstream.
 * Returns `ahead = 0, behind = 0` when there is no upstream configured.
 */
async gitAheadBehind(repoPath: string, branch: string) : Promise<Result<GitAheadBehind, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_ahead_behind", { repoPath, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the name of the currently checked-out branch.
 * Returns `GitError::DetachedHead` when in detached HEAD state.
 */
async gitCurrentBranch(repoPath: string) : Promise<Result<string, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_current_branch", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `git log -1` — full object id and first line of the commit message.
 */
async gitLastCommit(repoPath: string) : Promise<Result<GitHeadCommit, GitError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_last_commit", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane, positioning it on the monitor that contains the cursor.
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane.
 * On macOS, resigns key window status before hiding to avoid activating the main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the compiled-in default shortcut string.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut used to summon the quick pane.
 * Pass `None` to reset to the default shortcut.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enables or disables the quick pane by registering/unregistering its global shortcut.
 */
async setQuickPaneEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_quick_pane_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the zoom factor for a webview window (default: `"main"`).
 */
async setZoom(windowLabel: string | null, factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_zoom", { windowLabel, factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current zoom factor for a webview window (default: `"main"`).
 * Returns the last value set via `set_zoom`, or `1.0` if never zoomed.
 */
async getZoom(windowLabel: string | null) : Promise<number> {
    return await TAURI_INVOKE("get_zoom", { windowLabel });
},
/**
 * Set the same zoom factor on every open webview window.
 */
async broadcastZoom(factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_zoom", { factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the taskbar / dock progress bar on the main window.
 * 
 * `progress` — a value in `0..=100`; pass `None` to clear the indicator.
 */
async setProgressBar(progress: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_progress_bar", { progress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the outer position and size of a window (default: `"main"`).
 */
async getWindowBounds(windowLabel: string | null) : Promise<Result<WindowBounds, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_bounds", { windowLabel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the outer position and size of a window (default: `"main"`).
 */
async setWindowBounds(windowLabel: string | null, bounds: WindowBounds) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_bounds", { windowLabel, bounds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns `true` when running inside Windows Subsystem for Linux.
 * 
 * Checks `WSL_DISTRO_NAME` env var first (reliable since WSL 2), then
 * falls back to reading `/proc/version` for WSL 1 hosts.
 */
async isWsl() : Promise<boolean> {
    return await TAURI_INVOKE("is_wsl");
},
/**
 * Returns true if WSL is available on this system (Windows only).
 */
async wslIsAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("wsl_is_available");
},
/**
 * Lists installed WSL distributions (Windows only; empty list on other platforms).
 */
async wslListDistros() : Promise<Result<WslDistro[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wsl_list_distros") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Executes a shell command inside a WSL distro (Windows only).
 */
async wslExecute(distro: string, command: string, cwd: string | null) : Promise<Result<WslOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wsl_execute", { distro, command, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the current sandbox status for Claude CLI child processes.
 * On Linux: detects whether `bwrap` (bubblewrap) is available and active.
 * On macOS / Windows: always returns unavailable/inactive.
 */
async sandboxStatus() : Promise<SandboxStatus> {
    return await TAURI_INVOKE("sandbox_status");
},
/**
 * Returns the currently-known ports for sidecars that use port discovery.
 * A `None` entry means the sidecar hasn't announced its port yet.
 */
async getSidecarPorts() : Promise<SidecarPorts> {
    return await TAURI_INVOKE("get_sidecar_ports");
},
async checkAxiomregentAlive() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_axiomregent_alive") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bootGateStatus() : Promise<Result<BootGateStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("boot_gate_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spec 183 FR-T6 — boot-state Quit action. Today this is a thin wrapper
 * over `app.exit(0)` because spec 183 stage A/B doesn't yet hold the
 * sidecar `Child` handle past the announcement parse (see
 * `spawn_axiomregent`). Stage C will land child-handle retention and
 * promote this command to a SIGTERM-with-timeout-then-SIGKILL sequence
 * against the held handle before exit. The contract surface from the
 * frontend is stable — the implementation behind it tightens.
 */
async quitOpc() : Promise<void> {
    await TAURI_INVOKE("quit_opc");
},
async getPreflightSafetyTierReference() : Promise<SafetyTierRef[]> {
    return await TAURI_INVOKE("get_preflight_safety_tier_reference");
},
async getToolTierAssignments() : Promise<ToolTierEntry[]> {
    return await TAURI_INVOKE("get_tool_tier_assignments");
},
/**
 * Store a JWT in the OS keychain.
 */
async keychainStore(token: string, user: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_store", { token, user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve a JWT from the OS keychain. Returns None if not found.
 */
async keychainRetrieve(user: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_retrieve", { user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear a JWT from the OS keychain.
 */
async keychainClear(user: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_clear", { user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a project's clone token in the OS keychain.
 */
async cloneTokenStore(projectId: string, value: string, source: string, expiresAt: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_token_store", { projectId, value, source, expiresAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve a project's clone token. Returns None if no token is
 * stored for this project. A stored payload that fails to decode is
 * treated as a hard error so the cockpit can re-fetch from the
 * bundle endpoint instead of silently re-using a corrupt slot.
 */
async cloneTokenLoad(projectId: string) : Promise<Result<StoredCloneToken | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_token_load", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear a project's clone token (e.g. on workspace switch, project
 * deletion, or after a 401 + refresh cycle that invalidates the
 * previous credential).
 */
async cloneTokenClear(projectId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_token_clear", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the desktop OAuth login flow.
 * 
 * Generates a PKCE challenge, stores the flow in managed state, then opens
 * the user's default browser pointing at the statecraft authorize endpoint.
 * 
 * If `idp_hint` is provided (email address or OIDC provider ID), the flow
 * routes through the enterprise OIDC path instead of GitHub OAuth.
 */
async authStartLogin(idpHint: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_start_login", { idpHint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handle the deep-link callback from the OAuth provider.
 * 
 * Parses the `opc://auth/callback?code=...&state=...` URL, validates the
 * PKCE state, exchanges the code for tokens, and stores them.
 */
async authHandleCallback(url: string) : Promise<Result<AuthResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_handle_callback", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Complete multi-org selection after the initial token exchange.
 */
async authSelectOrg(pendingId: string, orgId: string) : Promise<Result<AuthResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_select_org", { pendingId, orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch to a different org — calls the org-switch API, stores new tokens.
 * 
 * Returns an AuthResult with the new org context.
 */
async authSwitchOrg(orgId: string) : Promise<Result<AuthResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_switch_org", { orgId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh the access token using the stored refresh token.
 * 
 * Returns the new `expires_at` Unix timestamp.
 */
async authRefreshToken() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_refresh_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current authentication status by reading the stored JWT.
 */
async authGetStatus() : Promise<Result<AuthStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all auth state — keychain entries and in-memory token.
 */
async authLogout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drain any deep-link auth callback URL that was captured before the frontend
 * registered its `auth-callback` listener (cold-launch). Returns `None` if
 * there is nothing pending.
 */
async authTakePendingCallback() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_take_pending_callback") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the base URL currently in effect (reflects the live client).
 */
async getStatecraftBaseUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_statecraft_base_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a new base URL, rebuild the client, and clear any stale auth
 * (tokens from a different server must not leak across).
 * 
 * Pass an empty string to disable the integration entirely.
 */
async setStatecraftBaseUrl(baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_statecraft_base_url", { baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthOrg = { org_id: string; org_slug: string; github_org_login?: string; org_display_name?: string; platform_role: string }
export type AuthResult = { type: "authenticated"; user: AuthUser; org: AuthOrg; expires_at: number } | { type: "org_selection"; pending_id: string; orgs: AuthOrg[]; user: AuthUser } | { type: "error"; code: string; message: string }
export type AuthStatus = { authenticated: boolean; user: AuthUser | null; org: AuthOrg | null; expires_at: number | null }
export type AuthUser = { id: string; email: string; name: string; github_login?: string; idp_provider?: string; idp_login?: string; avatar_url: string }
/**
 * Spec 183 — unified boot-gate status query. Combines FR-T1 (sidecar
 * liveness) and FR-T2 (org session materialised + sync.hello received)
 * into a single observable the boot-state UI subscribes to. Computed
 * fresh on every call; the frontend polls (not subscribes) during the
 * boot phase per FR-T4's explicit-retry posture.
 */
export type BootGateStatus = { 
/**
 * FR-T1: probe port announced AND TCP-connect succeeds.
 */
sidecar_alive: boolean; 
/**
 * FR-T2: StatecraftState has a non-empty org_id AND the duplex
 * consumer has received `sync.hello` from statecraft.
 */
org_session_ready: boolean; 
/**
 * Convenience: announced probe port (None if unannounced).
 */
axiomregent_port: number | null; 
/**
 * Convenience: org_id when present, for surface display only.
 */
org_id: string | null }
export type GitAheadBehind = { ahead: number; behind: number }
export type GitDiff = { stat: string; diff: string; files_changed: number; insertions: number; deletions: number }
export type GitError = { type: "NotFound"; message: string } | { type: "RefNotFound"; message: string } | { type: "DetachedHead" } | { type: "Other"; message: string }
/**
 * Latest commit on `HEAD` (`git log -1` — hash + first line of message).
 */
export type GitHeadCommit = { hash: string; message: string }
export type GitStatusEntry = { path: string; 
/**
 * "added", "modified", "deleted", "renamed", "untracked", "conflicted"
 */
status: string; staged: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type RecoveryError = { type: "FileNotFound" } | { type: "ValidationError"; message: string } | { type: "DataTooLarge"; max_bytes: number } | { type: "IoError"; message: string } | { type: "ParseError"; message: string }
/**
 * Read-only labels for safety tiers (governance UI).
 * Change tiers: `featuregraph::preflight::ChangeTier` (classifies file changes).
 * Tool tiers: `agent::safety::ToolTier` (classifies MCP tool dispatch).
 */
export type SafetyTierRef = { id: string; label: string; description: string }
export type SandboxStatus = { 
/**
 * True if a sandboxing method (bwrap) was found on PATH.
 */
available: boolean; 
/**
 * True if sandboxing is actively wrapping spawned CLI processes.
 */
active: boolean; 
/**
 * The sandboxing method in use, e.g. "bwrap". None when inactive.
 */
method: string | null }
export type SidecarPorts = { axiomregent: number | null }
/**
 * Persisted shape of a clone token. Mirrors `OpcBundleCloneToken` on
 * the wire side; `expires_at` is a string so we don't drag a date type
 * into the keychain layer (the value is whatever Statecraft returned).
 */
export type StoredCloneToken = { value: string; source: string; expires_at?: string | null }
/**
 * Per-tool tier assignments for governance UI (Feature 036).
 */
export type ToolTierEntry = { tool: string; tier: string }
export type UpdateError = { type: "NoUpdateAvailable" } | { type: "NetworkError"; message: string } | { type: "ChecksumMismatch" } | { type: "LaunchFailed"; message: string }
export type UpdateInfo = { 
/**
 * Version string without leading "v" (e.g. "0.2.0").
 */
version: string; 
/**
 * Release notes from the GitHub release body.
 */
notes: string; 
/**
 * Direct download URL for the platform installer asset.
 */
url: string; 
/**
 * Expected SHA-256 hex digest of the installer file.
 */
checksum: string }
export type WindowBounds = { x: number; y: number; width: number; height: number }
export type WslDistro = { name: string; is_default: boolean; state: string }
export type WslOutput = { stdout: string; stderr: string; exit_code: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
