// Spec 163 §7 — resolving the project's spec-spine source on disk.
//
// For projects produced by the substrate (spec 167, born-with kernel),
// the project's `.derived/spec-registry/by-spec/*.json` shards are
// generated by the project's own `spec-spine compile`. Spec 163 reads
// them via `spec-spine registry --repo <projectRoot>` (spec 217). For
// freshly-imported projects that have not yet run through the
// decomposition pipeline, the registry may be absent: that case surfaces
// as `null` here and the route renders the FR-007 empty-state CTA.
//
// The MVP path resolution is environment-driven:
//
//   STATECRAFT_PROJECT_REGISTRY_BASE=<dir>
//
// when set, the resolver looks under `<dir>/<projectId>/` for a project
// repo root containing `.derived/spec-registry/by-spec/` shards and a
// `specs/` directory. This is a clean fixture seam for tests and a
// natural mount-point for the future per-project registry mirroring
// path spec 167 will populate. When the env var is unset, or the
// expected files are missing, the resolver returns null and the view
// degrades to its empty state per FR-007.

import { access } from "node:fs/promises";
import { join, resolve } from "node:path";

export interface ProjectSpecRoots {
  /** Absolute path to the project repo root (the directory that owns specs/). */
  projectRoot: string;
  /**
   * Absolute path to the project's committed spec-registry shard directory
   * (`.derived/spec-registry/by-spec`). Spec 217 sharded the registry; the
   * reader passes `projectRoot` to `spec-spine --repo`, and this path is the
   * presence probe the resolver checks.
   */
  registryPath: string;
}

export interface ResolverOptions {
  /**
   * Override for STATECRAFT_PROJECT_REGISTRY_BASE. Tests pass this directly
   * to keep behaviour deterministic regardless of ambient env.
   */
  base?: string | null;
}

/**
 * Resolve `(projectRoot, registryPath)` for a projectId. Returns null
 * when no registry is available — the FR-007 empty-state case.
 *
 * The resolver does NOT consult the projects DB row directly: registry
 * presence is independent of project metadata. A project may exist
 * without a registry (newly imported); a registry may be present on
 * disk before the project row exists (test fixtures). The pairing is
 * established by the directory layout below the configured base.
 */
export async function resolveProjectRegistry(
  projectId: string,
  opts: ResolverOptions = {}
): Promise<ProjectSpecRoots | null> {
  const base = opts.base ?? process.env.statecraft_PROJECT_REGISTRY_BASE ?? null;
  if (!base) return null;

  const projectRoot = resolve(base, projectId);
  const registryPath = join(projectRoot, ".derived", "spec-registry", "by-spec");

  try {
    await access(registryPath);
  } catch {
    return null;
  }
  return { projectRoot, registryPath };
}
