//! Markdown renderer for the OAP-enriched codebase index.
//!
//! Cut D W-07b: moved from
//! `tools/codebase-indexer/src/render.rs`. Renders
//! `build/codebase-index/CODEBASE-INDEX.md` from the enriched
//! `index-oap.json`. The Makefile target and AGENTS.md init protocol
//! were redirected here in the same PR.

use crate::types::{AdapterRecord, Infrastructure, WorkflowTrace, WorkflowTraceSource};
// Spec 217 engine swap: decode the Layer 1-2 portion with the published
// library's codebase-index types (the in-tree codebase-indexer is retired).
use spec_spine_types::codebase::{
    Diagnostic, Diagnostics, IndexBuild, PackageKind, PackageRecord, TraceMapping, TraceSource,
    Traceability,
};
use serde::Deserialize;
use std::fs;
use std::path::Path;

/// Snapshot of the enriched index shape (Layers 1-5). Decoded from
/// `index-oap.json` for rendering. Field names mirror the
/// CodebaseIndex contract pre-W-07c; the renderer never sees the
/// generic `index.json` directly.
///
/// All fields are required: `index-oap.json` always emits the full
/// shape; missing-field decode errors here would surface enricher
/// bugs at render time.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EnrichedView {
    #[allow(dead_code)]
    schema_version: String,
    build: IndexBuild,
    packages: Vec<PackageRecord>,
    traceability: Traceability,
    factory: Vec<AdapterRecord>,
    infrastructure: Infrastructure,
    #[serde(rename = "workflowTraceability")]
    workflow_traceability: Vec<WorkflowTrace>,
    diagnostics: Diagnostics,
}

/// Render index-oap.json as a human-readable markdown document and
/// write it to `build/codebase-index/CODEBASE-INDEX.md`.
pub fn render_to_file(repo_root: &Path) -> Result<(), std::io::Error> {
    let path = repo_root.join(".derived/codebase-index/index-oap.json");
    let raw = fs::read_to_string(&path)?;
    let index: EnrichedView = serde_json::from_str(&raw)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    let markdown = render_markdown(&index);
    let out_path = repo_root.join(".derived/codebase-index/CODEBASE-INDEX.md");
    fs::write(out_path, markdown)?;
    Ok(())
}

fn render_markdown(index: &EnrichedView) -> String {
    let mut out = String::new();

    out.push_str("# Codebase Index — Open Agentic Platform\n\n");
    out.push_str(&format!(
        "> Auto-generated by `codebase-indexer` v{} (rendered by oap-code-index-enrich).\n",
        index.build.indexer_version
    ));
    out.push_str(&format!(
        "> Content hash: `{}`\n\n",
        index.build.content_hash
    ));

    // Layer 1: Inventory
    let rust_pkgs: Vec<_> = index
        .packages
        .iter()
        .filter(|p| {
            matches!(
                p.kind,
                PackageKind::RustLib | PackageKind::RustBin | PackageKind::RustLibBin
            )
        })
        .collect();
    let npm_pkgs: Vec<_> = index
        .packages
        .iter()
        .filter(|p| {
            matches!(
                p.kind,
                PackageKind::NpmPackage | PackageKind::NpmWorkspace
            )
        })
        .collect();

    out.push_str(&format!(
        "## Layer 1: Crate & Package Inventory ({} total)\n\n",
        index.packages.len()
    ));

    if !rust_pkgs.is_empty() {
        out.push_str(&format!("### Rust Crates ({})\n\n", rust_pkgs.len()));
        // Spec 217 engine swap: the library `PackageRecord` carries no
        // inter-crate dependency edges, so the former "Internal Deps" column is
        // dropped (the in-tree indexer that computed it is retired).
        out.push_str("| Name | Path | Kind | Version | Spec |\n");
        out.push_str("|------|------|------|---------|------|\n");
        for p in &rust_pkgs {
            let version = p.version.as_deref().unwrap_or("-");
            let spec = render_spec_link(p.spec_ref.as_deref());
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                p.name,
                p.path,
                kind_label(&p.kind),
                version,
                spec
            ));
        }
        out.push('\n');
    }

    if !npm_pkgs.is_empty() {
        out.push_str(&format!("### NPM Packages ({})\n\n", npm_pkgs.len()));
        out.push_str("| Name | Path | Kind | Version | Spec |\n");
        out.push_str("|------|------|------|---------|------|\n");
        for p in &npm_pkgs {
            let version = p.version.as_deref().unwrap_or("-");
            let spec = render_spec_link(p.spec_ref.as_deref());
            out.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                p.name,
                p.path,
                kind_label(&p.kind),
                version,
                spec
            ));
        }
        out.push('\n');
    }

    // Layer 2: Traceability
    let mappings = &index.traceability.mappings;
    out.push_str(&format!(
        "## Layer 2: Spec → Code Traceability ({} mapped, {} orphaned specs, {} untraced paths)\n\n",
        mappings.len(),
        index.traceability.orphaned_specs.len(),
        index.traceability.untraced_code.len()
    ));

    let implements_rows: Vec<&TraceMapping> = mappings
        .iter()
        .filter(|m| !m.implementing_paths.is_empty())
        .collect();
    let amend_rows: Vec<&TraceMapping> = mappings
        .iter()
        .filter(|m| !m.amends.is_empty() || m.amendment_record.is_some())
        .collect();

    if !implements_rows.is_empty() {
        out.push_str(&format!(
            "### Implements ({} specs claim implementing paths)\n\n",
            implements_rows.len()
        ));
        out.push_str("| Spec | Status | Paths (source) |\n");
        out.push_str("|------|--------|----------------|\n");
        for m in &implements_rows {
            let status = m.spec_status.as_deref().unwrap_or("-");
            let mut paths = Vec::new();
            for p in &m.implementing_paths {
                let source = match p.source {
                    TraceSource::SpecEdge => "spec-edge",
                    TraceSource::ManifestMetadata => "manifest-metadata",
                    TraceSource::CommentHeader => "comment-header",
                    TraceSource::Multiple => "multiple",
                };
                paths.push(format!("`{}` ({})", p.path, source));
            }
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                m.spec_id,
                status,
                paths.join("<br/>")
            ));
        }
        out.push('\n');
    }

    if !amend_rows.is_empty() {
        out.push_str(&format!(
            "### Amends ({} amendments declared)\n\n",
            amend_rows.len()
        ));
        out.push_str("| Spec | amends | amendmentRecord |\n");
        out.push_str("|------|--------|------------------|\n");
        for m in &amend_rows {
            let amends = if m.amends.is_empty() {
                "-".to_string()
            } else {
                m.amends
                    .iter()
                    .map(|a| format!("`{a}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let record = m
                .amendment_record
                .as_deref()
                .map(|r| format!("`{r}`"))
                .unwrap_or_else(|| "-".to_string());
            out.push_str(&format!("| `{}` | {} | {} |\n", m.spec_id, amends, record));
        }
        out.push('\n');
    }

    // Layer 3: Factory adapters
    if !index.factory.is_empty() {
        out.push_str(&format!(
            "## Layer 3: Factory Adapters ({} total)\n\n",
            index.factory.len()
        ));
        out.push_str("| Adapter | Target stack | Language | Runtime | Phase coverage |\n");
        out.push_str("|---------|--------------|----------|---------|----------------|\n");
        for a in &index.factory {
            let stack = a.target_stack.as_deref().unwrap_or("-");
            let lang = a.stack_language.as_deref().unwrap_or("-");
            let runtime = a.stack_runtime.as_deref().unwrap_or("-");
            let stages = a
                .phase_coverage
                .as_ref()
                .map(|p| p.join(", "))
                .unwrap_or_else(|| "-".to_string());
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                a.name, stack, lang, runtime, stages
            ));
        }
        out.push('\n');
    }

    // Layer 4: Infrastructure
    out.push_str("## Layer 4: Infrastructure\n\n");
    render_named_section(
        &mut out,
        "Tools",
        &index
            .infrastructure
            .tools
            .iter()
            .map(|t| (&t.name as &str, &t.path as &str))
            .collect::<Vec<_>>(),
    );
    render_named_section(
        &mut out,
        "Agents",
        &index
            .infrastructure
            .agents
            .iter()
            .map(|e| (e.name.as_str(), e.path.as_str()))
            .collect::<Vec<_>>(),
    );
    render_named_section(
        &mut out,
        "Commands",
        &index
            .infrastructure
            .commands
            .iter()
            .map(|e| (e.name.as_str(), e.path.as_str()))
            .collect::<Vec<_>>(),
    );
    render_named_section(
        &mut out,
        "Rules",
        &index
            .infrastructure
            .rules
            .iter()
            .map(|e| (e.name.as_str(), e.path.as_str()))
            .collect::<Vec<_>>(),
    );
    render_named_section(
        &mut out,
        "Schemas",
        &index
            .infrastructure
            .schemas
            .iter()
            .map(|e| (e.name.as_str(), e.path.as_str()))
            .collect::<Vec<_>>(),
    );

    // Layer 5: Workflow Traceability
    if !index.workflow_traceability.is_empty() {
        out.push_str(&format!(
            "## Layer 5: CI Workflow Traceability ({} total)\n\n",
            index.workflow_traceability.len()
        ));
        out.push_str("| Workflow | Specs | Source |\n");
        out.push_str("|----------|-------|--------|\n");
        for trace in &index.workflow_traceability {
            let specs = if trace.specs.is_empty() {
                "—".to_string()
            } else {
                trace.specs.join(", ")
            };
            let source = match trace.source {
                WorkflowTraceSource::Header => "header",
                WorkflowTraceSource::Allowlist => "allowlist",
                WorkflowTraceSource::Unmapped => "unmapped",
            };
            out.push_str(&format!("| `{}` | {} | {} |\n", trace.path, specs, source));
        }
        out.push('\n');
    }

    // Diagnostics
    if !index.diagnostics.warnings.is_empty() || !index.diagnostics.errors.is_empty() {
        out.push_str("## Diagnostics\n\n");
        if !index.diagnostics.errors.is_empty() {
            out.push_str(&format!(
                "### Errors ({})\n\n",
                index.diagnostics.errors.len()
            ));
            render_diagnostics_table(&mut out, &index.diagnostics.errors);
        }
        if !index.diagnostics.warnings.is_empty() {
            out.push_str(&format!(
                "### Warnings ({})\n\n",
                index.diagnostics.warnings.len()
            ));
            render_diagnostics_table(&mut out, &index.diagnostics.warnings);
        }
    }

    out
}

fn render_named_section(out: &mut String, title: &str, items: &[(&str, &str)]) {
    if items.is_empty() {
        return;
    }
    out.push_str(&format!("### {} ({})\n\n", title, items.len()));
    out.push_str("| Name | Path |\n");
    out.push_str("|------|------|\n");
    for (name, path) in items {
        out.push_str(&format!("| {} | `{}` |\n", name, path));
    }
    out.push('\n');
}

fn render_diagnostics_table(out: &mut String, diagnostics: &[Diagnostic]) {
    out.push_str("| Code | Path | Message |\n");
    out.push_str("|------|------|---------|\n");
    for d in diagnostics {
        let path = d.path.as_deref().unwrap_or("-");
        out.push_str(&format!("| `{}` | `{}` | {} |\n", d.code, path, d.message));
    }
    out.push('\n');
}

fn render_spec_link(spec_ref: Option<&str>) -> String {
    match spec_ref {
        Some(s) => format!("[`{s}`](../../specs/{s}/spec.md)"),
        None => "—".to_string(),
    }
}

fn kind_label(k: &PackageKind) -> &'static str {
    match k {
        PackageKind::RustLib => "rust-lib",
        PackageKind::RustBin => "rust-bin",
        PackageKind::RustLibBin => "rust-libbin",
        PackageKind::NpmPackage => "npm-package",
        PackageKind::NpmWorkspace => "npm-workspace",
    }
}
