// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent/skill execution type. Superset of `SkillType` from skill-factory.
 *
 * - `prompt`, `agent`, `headless` correspond to the original `SkillType` variants.
 * - `process` and `scaffold` are factory-specific (Tier 1 and Tier 2 respectively).
 */
export type AgentType = "prompt" | "agent" | "headless" | "process" | "scaffold";
