// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Governance requirement for agent execution. Connects to spec 098's `governance_mode`.
 */
export type GovernanceRequirement = "none" | "advisory" | "enforced";
