// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Handler type for hook declarations inside frontmatter.
 */
export type HookHandlerType = "bash" | "agent" | "prompt";
