// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookHandlerType } from "./HookHandlerType";

/**
 * A single hook declaration inside an agent or skill's frontmatter.
 */
export type HookDeclaration = { name: string, type: HookHandlerType, 
/**
 * Optional condition expression (e.g. `"tool == 'Bash' && ..."`).
 */
if?: string | null, 
/**
 * Command or template to execute.
 */
run: string, };
