/**
 * Barrel module for the agent-frontmatter TS mirror (spec 111 §2.1).
 *
 * The sibling `*.ts` files are generated by `ts-rs` from
 * `crates/agent-frontmatter/src/types.rs`. The generator is invoked on every
 * `cargo test` (see `crates/agent-frontmatter/tests/ts_bindings.rs`) and
 * `make ci` runs `git diff --exit-code` afterwards, so drift between the
 * Rust type and the TS mirror is an immediate CI failure.
 *
 * This file is the only hand-maintained entry in this directory. It exists
 * because the Rust `UnifiedFrontmatter` uses `#[serde(flatten)]` to preserve
 * unknown fields (`extra: HashMap<String, serde_json::Value>` — spec 054
 * FR-013) and `ts-rs` cannot express an open index signature on a named
 * struct.
 *
 * Encore's schema parser rejects an index signature combined with additional
 * named fields on the same type (see spec 111 §2.1). To satisfy the parser
 * while still preserving the Rust `extra` flatten map on the wire, the
 * `CatalogFrontmatter` alias below is a plain `Record<string, unknown>` —
 * an index signature on its own is accepted. The richly-typed
 * `UnifiedFrontmatter` is still re-exported and can be used for typed
 * internal access when a caller needs structured access to known fields.
 */

export type { AgentType } from "./AgentType";
export type { GovernanceRequirement } from "./GovernanceRequirement";
export type { HookDeclaration } from "./HookDeclaration";
export type { HookHandlerType } from "./HookHandlerType";
export type { MutationCapability } from "./MutationCapability";
export type { SafetyTier } from "./SafetyTier";
export type { UnifiedFrontmatter } from "./UnifiedFrontmatter";

/**
 * Wire shape stored in `agent_catalog.frontmatter` (JSONB) and carried on
 * `agent.catalog.updated` envelopes. Expressed as `Record<string, unknown>`
 * so Encore's schema parser can handle it; the structured field set lives on
 * the Rust side (`crates/agent-frontmatter::UnifiedFrontmatter`) and in the
 * sibling `UnifiedFrontmatter.ts` generated mirror for typed consumers.
 */
export type CatalogFrontmatter = Record<string, unknown>;
