/**
 * The chassis/tree boundary (spec 035 §4).
 *
 * Two mechanisms, tested for the property each exists to guarantee rather than
 * for its happy path: the composer must REFUSE the collisions that would widen
 * a ceiling invisibly, and the preflight must NOTICE the local edits an upgrade
 * would discard. A composer that merges quietly and a preflight that reports
 * nothing both look like success.
 */
import { describe, expect, it, vi } from "vitest";

import { compose } from "./gen-manifest.mjs";
import { classify } from "./chassis-lock.mjs";

const chassis = {
  app: { name: "enrahitu", org: "statecrafting" },
  capabilities: [
    { id: "cap.db.state.read", kind: "db.read", resource: "state" },
    { id: "cap.db.state.txn", kind: "db.txn", resource: "state" },
  ],
  services: {
    control: { tier: "ts", role: "library", capabilities: ["cap.db.state.read"] },
    web: { tier: "ts", capabilities: [] },
  },
  resources: { databases: [{ name: "state", engine: "hiqlite" }] },
  gate: { checks: ["secrets"] },
  trust: { levels: ["full"] },
};

/** The composer exits the process on refusal; capture that as a throw. */
function refusal(overlay: Record<string, unknown>): string {
  const errors: string[] = [];
  const err = vi.spyOn(console, "error").mockImplementation((m) => void errors.push(String(m)));
  const exit = vi.spyOn(process, "exit").mockImplementation(((): never => {
    throw new Error("EXIT");
  }) as never);
  try {
    compose(chassis, overlay);
    return "";
  } catch {
    return errors.join("\n");
  } finally {
    err.mockRestore();
    exit.mockRestore();
  }
}

describe("the manifest composer (spec 035 §3.3)", () => {
  it("adds an overlay capability and sorts the result deterministically", () => {
    const out = compose(chassis, {
      capabilities: [{ id: "cap.db.state.txn.grants", kind: "db.txn", resource: "state" }],
    });
    const ids = out.capabilities.map((c: { id: string }) => c.id);
    expect(ids).toEqual([...ids].sort());
    expect(ids).toContain("cap.db.state.txn.grants");
    expect(ids).toContain("cap.db.state.read");
  });

  it("refuses to redefine a chassis capability rather than letting precedence widen a ceiling", () => {
    const message = refusal({
      capabilities: [{ id: "cap.db.state.read", kind: "db.write", resource: "state" }],
    });
    expect(message).toMatch(/redefines chassis capability 'cap.db.state.read'/);
    expect(message).toMatch(/widened ceiling/);
  });

  it("adds a new service whole", () => {
    const out = compose(chassis, {
      services: { grants: { tier: "ts", capabilities: ["cap.db.state.read"] } },
    });
    expect(out.services.grants).toEqual({ tier: "ts", capabilities: ["cap.db.state.read"] });
  });

  it("lets an overlay add grants to a chassis service, additively and deduplicated", () => {
    const out = compose(chassis, {
      services: { control: { capabilities: ["cap.db.state.txn", "cap.db.state.read"] } },
    });
    expect(out.services.control.capabilities).toEqual(["cap.db.state.read", "cap.db.state.txn"]);
    // Everything else about the chassis service survives untouched.
    expect(out.services.control.role).toBe("library");
  });

  it("refuses to redefine anything but capabilities on a chassis service", () => {
    expect(refusal({ services: { control: { tier: "rust" } } })).toMatch(
      /redefines 'tier' on chassis service 'control'/,
    );
  });

  it("refuses a chassis-owned top-level member, naming what an overlay may set", () => {
    const message = refusal({ gate: { checks: ["secrets", "egress"] } });
    expect(message).toMatch(/sets chassis-owned member\(s\): gate/);
    expect(message).toMatch(/capabilities, services and resources/);
  });

  it("adds a resource but refuses to redefine one a chassis capability is granted on", () => {
    const added = compose(chassis, { resources: { databases: [{ name: "grants", engine: "hiqlite" }] } });
    expect(added.resources.databases.map((d: { name: string }) => d.name)).toEqual(["grants", "state"]);
    expect(refusal({ resources: { databases: [{ name: "state", engine: "coreledger-libsql" }] } })).toMatch(
      /redefines chassis resource 'databases\/state'/,
    );
  });

  it("stamps the derived file so nobody edits it by hand", () => {
    expect(compose(chassis, {})["//"]).toMatch(/GENERATED by scripts\/gen-manifest\.mjs/);
  });
});

describe("the upgrade preflight (spec 035 §3.2)", () => {
  const lock = {
    version: 1,
    files: { "backend/a.ts": "aaa", "backend/b.ts": "bbb", "docker/c.sh": "ccc" },
  };

  it("reports an unmodified tree as safe to upgrade", () => {
    const result = classify(lock, { version: 1, files: { ...lock.files } });
    expect(result).toEqual({ unmodified: 3, modified: [], removed: [], added: [] });
  });

  it("names the edited chassis files an upgrade would discard", () => {
    const result = classify(lock, {
      version: 1,
      files: { ...lock.files, "backend/b.ts": "EDITED" },
    });
    expect(result.modified).toEqual(["backend/b.ts"]);
    expect(result.unmodified).toBe(2);
  });

  it("treats a locally deleted chassis file the same as an edited one", () => {
    const files = { ...lock.files };
    delete (files as Record<string, string>)["docker/c.sh"];
    expect(classify(lock, { version: 1, files }).removed).toEqual(["docker/c.sh"]);
  });

  it("reports a new file in a chassis root without calling it a hazard", () => {
    const result = classify(lock, {
      version: 1,
      files: { ...lock.files, "backend/new.ts": "nnn" },
    });
    expect(result.added).toEqual(["backend/new.ts"]);
    expect(result.modified).toEqual([]);
  });
});
