import { api, APIError } from "encore.dev/api";
import { db } from "../db/drizzle";
import { FactoryEventTopic } from "./events";
import adapterScopesData from "./adapter-scopes.json";
import {
  projects,
  factoryPipelines,
  factoryBusinessDocs,
  factoryStages,
  factoryScaffoldFeatures,
  factoryAuditLog,
  factoryPolicyBundles,
  factoryArtifacts,
  promotions,
} from "../db/schema";
import { and, eq, desc, gte, asc, sql } from "drizzle-orm";
import { loadSubstrateForOrg } from "./substrateBrowser";
import { listAdapterViews } from "./adapterView";
import { resolveKnowledgeForFactory } from "../knowledge/knowledge";
import { publishFactoryRunRequest } from "../sync/relay";

// Spec 199 FR-002 — there is no static adapter union; adapters are whatever
// the substrate's manifests self-declare. Validation happens against the
// org's substrate at the call site.

// ---------------------------------------------------------------------------
// Factory pipeline stages (7-stage pipeline)
// ---------------------------------------------------------------------------

const PIPELINE_STAGES = [
  "s0-preflight",
  "s1-business-requirements",
  "s2-service-requirements",
  "s3-data-model",
  "s4-api-spec",
  "s5-ui-spec",
  "s6-scaffolding",
] as const;

// ---------------------------------------------------------------------------
// Stage status transitions allowed for confirm/reject
// ---------------------------------------------------------------------------

const CONFIRMABLE_STATUSES = ["completed", "in_progress"] as const;

// ---------------------------------------------------------------------------
// Default policy rules (merged with org overrides)
// ---------------------------------------------------------------------------

// Adapter-specific scopes — a DERIVED PROJECTION of the admitted adapter
// sub-envelope(s) (manifest `governance:` section, spec 198 FR-012),
// generated by adapter-scopes-compiler from the factory source. One home
// per fact: the manifest declares, this snapshot materialises enforcement.
// Imported statically so Encore's compiler bundles it into the build.
//
// There is deliberately NO default fallback: an adapter absent from the
// snapshot has no materialised sub-envelope, and inventing a scope for it
// (the retired DEFAULT_SCOPE granted npm/npx/node + src/) would hand a
// BROADER allowlist to exactly the adapter whose governance is least
// established. Fail closed; regenerate the snapshot instead.
const ADAPTER_SCOPES: Record<string, { file_write_scope: string[]; allowed_commands: string[] }> =
  adapterScopesData.adapters ?? {};

// Spec 201 phase 3 reads this policy fact to render the run-detail HITL
// gate surface; one home for the stage-approval list (the spec 201
// approval-context endpoint maps N → `sN` stage ids).
export const DEFAULT_REQUIRE_STAGE_APPROVAL = [1, 2, 3]; // s1, s2, s3

function compileDefaultRules(adapter: string, overrides?: PolicyOverrides) {
  const scope = Object.hasOwn(ADAPTER_SCOPES, adapter)
    ? ADAPTER_SCOPES[adapter]
    : undefined;
  if (!scope) {
    throw APIError.failedPrecondition(
      `adapter "${adapter}" has no entry in the adapter-scopes enforcement ` +
        `snapshot (spec 198 FR-012) — regenerate it from the admitted ` +
        `manifest with adapter-scopes-compiler before initializing pipelines`
    );
  }
  return {
    allowed_adapters: [adapter],
    max_retry_per_feature: overrides?.max_retry_per_feature ?? 3,
    require_stage_approval: DEFAULT_REQUIRE_STAGE_APPROVAL, // human sign-off
    auto_approve_stages: [0, 4, 5, 6],  // s0, s4, s5, s6 auto-proceed
    token_budget: {
      per_stage_agent: overrides?.token_budget_total
        ? Math.floor(overrides.token_budget_total / 7)
        : 300000,
      per_feature_agent: 50000,
      total_pipeline: overrides?.token_budget_total ?? 2000000,
    },
    file_write_scope: scope.file_write_scope,
    allowed_commands: scope.allowed_commands,
    blocked_patterns: ["rm -rf", "sudo", "curl | sh"],
  };
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type PolicyOverrides = {
  max_retry_per_feature?: number;
  token_budget_total?: number;
};

type BusinessDocRef = {
  name: string;
  storage_ref: string;
};

type PipelineRow = {
  id: string;
  projectId: string;
  adapterName: string;
  status: string;
  policyBundleId: string | null;
  buildSpecHash: string | null;
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
};

type AuditEntry = {
  id: string;
  pipelineId: string;
  timestamp: Date;
  event: string;
  actor: string | null;
  stageId: string | null;
  featureId: string | null;
  details: unknown;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function verifyProjectInScope(
  projectId: string,
  orgId: string
): Promise<void> {
  const rows = await db
    .select({ id: projects.id })
    .from(projects)
    .where(and(eq(projects.id, projectId), eq(projects.orgId, orgId)))
    .limit(1);

  if (rows.length === 0) {
    throw APIError.notFound("project not found");
  }
}

async function getActivePipeline(
  projectId: string,
  orgId: string
): Promise<PipelineRow> {
  // Org-scoped: verify project belongs to caller's org (spec 119).
  await verifyProjectInScope(projectId, orgId);

  const rows = await db
    .select()
    .from(factoryPipelines)
    .where(eq(factoryPipelines.projectId, projectId))
    .orderBy(desc(factoryPipelines.createdAt))
    .limit(1);

  if (rows.length === 0) {
    throw APIError.notFound("no Factory pipeline found for this project");
  }
  return rows[0];
}

async function appendAudit(
  entry: {
    pipelineId: string;
    event: string;
    actor?: string;
    stageId?: string;
    featureId?: string;
    details?: Record<string, unknown>;
  },
  txDb?: typeof db,
): Promise<string> {
  const d = txDb ?? db;
  const [row] = await d
    .insert(factoryAuditLog)
    .values({
      pipelineId: entry.pipelineId,
      event: entry.event,
      actor: entry.actor ?? null,
      stageId: entry.stageId ?? null,
      featureId: entry.featureId ?? null,
      details: entry.details ?? {},
    })
    .returning({ id: factoryAuditLog.id });
  return row.id;
}

// ---------------------------------------------------------------------------
// FR-001: Factory Project Initialization
// ---------------------------------------------------------------------------

type PipelineSource = "opc-direct" | "statecraft";

type InitRequest = {
  id: string; // project ID (path param)
  adapter: string;
  business_docs?: BusinessDocRef[];
  knowledge_object_ids?: string[]; // spec 087: resolve project knowledge objects
  policy_overrides?: PolicyOverrides;
  /**
   * Trigger path for this pipeline (spec 110 §8 Rollout Phase 6 — default
   * flipped to `"statecraft"`; OPC-direct remains available for offline
   * workflows and for the desktop's dual-write path).
   *
   *   - "statecraft" (default): statecraft dispatches a `factory.run.request`
   *     through the duplex channel so a connected OPC executes the run.
   *     Used by the web Initialize button and `oap-ctl run factory`.
   *   - "opc-direct": the caller is already running the engine locally; no
   *     envelope is dispatched. Callers on this path (notably the desktop's
   *     `start_factory_pipeline` dual-write) MUST set this explicitly to
   *     avoid a self-dispatch loop.
   */
  source?: PipelineSource;
  actorUserId: string;
  orgId: string;
};

type InitResponse = {
  pipeline_id: string;
  adapter: string;
  policy_bundle_id: string;
  status: string;
  source: PipelineSource;
  created_at: string;
};

export const initPipeline = api(
  { expose: true, auth: true, method: "POST", path: "/api/projects/:id/factory/init" },
  async (req: InitRequest): Promise<InitResponse> => {
    await verifyProjectInScope(req.id, req.orgId);

    // Validate adapter against the org's substrate-declared manifests
    // (spec 199 FR-002 — manifest-sourced identity, no static union).
    const substrateForAdapter = await loadSubstrateForOrg(req.orgId);
    const knownAdapters = listAdapterViews(substrateForAdapter).map(
      (a) => a.name,
    );
    if (!knownAdapters.includes(req.adapter)) {
      throw APIError.invalidArgument(
        `unknown adapter "${req.adapter}". Known adapters: ${knownAdapters.join(", ") || "(none synced)"}`
      );
    }

    // Resolve knowledge objects into business doc refs (spec 087 Phase 2)
    let knowledgeDocs: BusinessDocRef[] = [];
    if (req.knowledge_object_ids && req.knowledge_object_ids.length > 0) {
      knowledgeDocs = await resolveKnowledgeForFactory(
        req.id,
        req.knowledge_object_ids
      );
    }

    // Merge explicit business_docs with resolved knowledge objects
    const allDocs = [...(req.business_docs ?? []), ...knowledgeDocs];

    const source: PipelineSource = req.source ?? "statecraft";

    // All inserts in a single transaction to prevent orphaned rows
    const result = await db.transaction(async (tx) => {
      // Compile policy bundle
      const rules = compileDefaultRules(req.adapter, req.policy_overrides);
      const [bundle] = await tx
        .insert(factoryPolicyBundles)
        .values({
          projectId: req.id,
          adapterName: req.adapter,
          rules,
        })
        .returning();

      // Find most recent completed pipeline for same project+adapter (082 FR-022)
      const prevRows = await tx
        .select({ id: factoryPipelines.id })
        .from(factoryPipelines)
        .where(
          and(
            eq(factoryPipelines.projectId, req.id),
            eq(factoryPipelines.adapterName, req.adapter),
            eq(factoryPipelines.status, "completed")
          )
        )
        .orderBy(desc(factoryPipelines.createdAt))
        .limit(1);

      const previousPipelineId = prevRows.length > 0 ? prevRows[0].id : null;

      // Create pipeline
      const [pipeline] = await tx
        .insert(factoryPipelines)
        .values({
          projectId: req.id,
          adapterName: req.adapter,
          policyBundleId: bundle.id,
          previousPipelineId,
          source,
        })
        .returning();

      // Store business document references (explicit + knowledge-resolved)
      if (allDocs.length > 0) {
        await tx.insert(factoryBusinessDocs).values(
          allDocs.map((doc) => ({
            pipelineId: pipeline.id,
            name: doc.name,
            storageRef: doc.storage_ref,
          }))
        );
      }

      // Seed stage rows
      await tx.insert(factoryStages).values(
        PIPELINE_STAGES.map((stageId) => ({
          pipelineId: pipeline.id,
          stageId,
        }))
      );

      // Audit entry
      await appendAudit(
        {
          pipelineId: pipeline.id,
          event: "pipeline_initialized",
          actor: req.actorUserId,
          details: {
            adapter: req.adapter,
            doc_count: allDocs.length,
            knowledge_object_ids: req.knowledge_object_ids ?? [],
            policy_bundle_id: bundle.id,
            source,
          },
        },
        tx as unknown as typeof db,
      );

      return { pipeline, bundle };
    });

    await FactoryEventTopic.publish({
      project_id: req.id,
      pipeline_id: result.pipeline.id,
      event_type: "pipeline_initialized",
      actor: req.actorUserId,
      details: { adapter: req.adapter, doc_count: allDocs.length, source },
    });

    // Spec 110 §8 Rollout Phase 3: dispatch the duplex `factory.run.request`
    // only when the trigger path was `statecraft`. OPC-direct runs still
    // execute the legacy local path; their envelope dispatch is a no-op.
    if (source === "statecraft") {
      await publishFactoryRunRequest({
        orgId: req.orgId,
        projectId: req.id,
        pipelineId: result.pipeline.id,
        adapter: req.adapter,
        actorUserId: req.actorUserId,
        knowledgeObjectIds: req.knowledge_object_ids ?? [],
        businessDocs: (req.business_docs ?? []).map((d) => ({
          name: d.name,
          storageRef: d.storage_ref,
        })),
        policyBundleId: result.bundle.id,
      });
    }

    return {
      pipeline_id: result.pipeline.id,
      adapter: result.pipeline.adapterName,
      policy_bundle_id: result.bundle.id,
      status: result.pipeline.status,
      source,
      created_at: result.pipeline.createdAt.toISOString(),
    };
  }
);

// ---------------------------------------------------------------------------
// FR-002: Pipeline Status
// ---------------------------------------------------------------------------

type StatusResponse = {
  pipeline_id: string;
  status: string;
  adapter: string;
  current_stage: string | null;
  stages: Record<
    string,
    {
      status: string;
      started_at?: string;
      completed_at?: string;
      confirmed_by?: string;
      confirmed_at?: string;
    }
  >;
  policy_bundle: unknown | null;
  token_spend: {
    total: number;
    budget: number;
    by_stage: Record<string, number>;
  };
  started_at: string | null;
};

export const getStatus = api(
  { expose: true, auth: true, method: "GET", path: "/api/projects/:id/factory/status" },
  async (req: { id: string; orgId: string }): Promise<StatusResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    // Stages
    const stageRows = await db
      .select()
      .from(factoryStages)
      .where(eq(factoryStages.pipelineId, pipeline.id))
      .orderBy(asc(factoryStages.stageId));

    const stages: StatusResponse["stages"] = {};
    let currentStage: string | null = null;

    for (const s of stageRows) {
      stages[s.stageId] = {
        status: s.status,
        ...(s.startedAt && { started_at: s.startedAt.toISOString() }),
        ...(s.completedAt && { completed_at: s.completedAt.toISOString() }),
        ...(s.confirmedBy && { confirmed_by: s.confirmedBy }),
        ...(s.confirmedAt && { confirmed_at: s.confirmedAt.toISOString() }),
      };
      if (s.status === "in_progress") {
        currentStage = s.stageId;
      }
    }

    // Token spend
    const stageTokens = stageRows.reduce(
      (acc, s) => {
        const total = (s.promptTokens ?? 0) + (s.completionTokens ?? 0);
        if (total > 0) acc[s.stageId] = total;
        return acc;
      },
      {} as Record<string, number>
    );

    const scaffoldRows = await db
      .select({
        promptTokens: factoryScaffoldFeatures.promptTokens,
        completionTokens: factoryScaffoldFeatures.completionTokens,
      })
      .from(factoryScaffoldFeatures)
      .where(eq(factoryScaffoldFeatures.pipelineId, pipeline.id));

    const scaffoldTotal = scaffoldRows.reduce(
      (acc, r) => acc + (r.promptTokens ?? 0) + (r.completionTokens ?? 0),
      0
    );

    const stageTotal = Object.values(stageTokens).reduce((a, b) => a + b, 0);
    const totalSpend = stageTotal + scaffoldTotal;

    // Policy bundle
    let policyBundle: unknown | null = null;
    if (pipeline.policyBundleId) {
      const bundles = await db
        .select()
        .from(factoryPolicyBundles)
        .where(eq(factoryPolicyBundles.id, pipeline.policyBundleId))
        .limit(1);
      if (bundles.length > 0) {
        policyBundle = bundles[0].rules;
      }
    }

    return {
      pipeline_id: pipeline.id,
      status: pipeline.status,
      adapter: pipeline.adapterName,
      current_stage: currentStage,
      stages,
      policy_bundle: policyBundle,
      token_spend: {
        total: totalSpend,
        budget: (policyBundle as { token_budget?: { total_pipeline?: number } })
          ?.token_budget?.total_pipeline ?? 2000000,
        by_stage: stageTokens,
      },
      started_at: pipeline.startedAt?.toISOString() ?? null,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-004: Stage Confirmation
// ---------------------------------------------------------------------------

type ConfirmRequest = {
  id: string; // project ID
  stageId: string;
  notes?: string;
  actorUserId: string;
  orgId: string;
};

type ConfirmResponse = {
  stage: string;
  confirmed_by: string;
  confirmed_at: string;
  audit_entry_id: string;
};

export const confirmStage = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/stage/:stageId/confirm",
  },
  async (req: ConfirmRequest): Promise<ConfirmResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);
    const now = new Date();

    // Find stage
    const stageRows = await db
      .select()
      .from(factoryStages)
      .where(
        and(
          eq(factoryStages.pipelineId, pipeline.id),
          eq(factoryStages.stageId, req.stageId)
        )
      )
      .limit(1);

    if (stageRows.length === 0) {
      throw APIError.notFound(`stage "${req.stageId}" not found`);
    }

    // Guard: only confirmable statuses
    const stage = stageRows[0];
    if (stage.status === "confirmed") {
      throw APIError.failedPrecondition(
        `stage "${req.stageId}" is already confirmed`
      );
    }
    if (!CONFIRMABLE_STATUSES.includes(stage.status as typeof CONFIRMABLE_STATUSES[number])) {
      throw APIError.failedPrecondition(
        `stage "${req.stageId}" has status "${stage.status}" and cannot be confirmed`
      );
    }

    // Update stage
    await db
      .update(factoryStages)
      .set({
        status: "confirmed",
        confirmedBy: req.actorUserId,
        confirmedAt: now,
      })
      .where(eq(factoryStages.id, stage.id));

    // Audit
    const auditId = await appendAudit({
      pipelineId: pipeline.id,
      event: "stage_confirmed",
      actor: req.actorUserId,
      stageId: req.stageId,
      details: { notes: req.notes },
    });

    await FactoryEventTopic.publish({
      project_id: req.id,
      pipeline_id: pipeline.id,
      event_type: "stage_confirmed",
      stage_id: req.stageId,
      actor: req.actorUserId,
      details: { notes: req.notes },
    });

    return {
      stage: req.stageId,
      confirmed_by: req.actorUserId,
      confirmed_at: now.toISOString(),
      audit_entry_id: auditId,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-005: Stage Rejection
// ---------------------------------------------------------------------------

type RejectRequest = {
  id: string;
  stageId: string;
  feedback: string;
  actorUserId: string;
  orgId: string;
};

type RejectResponse = {
  stage: string;
  rejected_by: string;
  rejected_at: string;
  feedback: string;
  audit_entry_id: string;
};

export const rejectStage = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/stage/:stageId/reject",
  },
  async (req: RejectRequest): Promise<RejectResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);
    const now = new Date();

    if (!req.feedback) {
      throw APIError.invalidArgument("feedback is required for rejection");
    }

    // Find stage
    const stageRows = await db
      .select()
      .from(factoryStages)
      .where(
        and(
          eq(factoryStages.pipelineId, pipeline.id),
          eq(factoryStages.stageId, req.stageId)
        )
      )
      .limit(1);

    if (stageRows.length === 0) {
      throw APIError.notFound(`stage "${req.stageId}" not found`);
    }

    // Guard: cannot reject already-rejected or confirmed stages
    const stage = stageRows[0];
    if (stage.status === "rejected") {
      throw APIError.failedPrecondition(
        `stage "${req.stageId}" is already rejected`
      );
    }
    if (stage.status === "confirmed") {
      throw APIError.failedPrecondition(
        `stage "${req.stageId}" is already confirmed and cannot be rejected`
      );
    }

    // Update stage
    await db
      .update(factoryStages)
      .set({
        status: "rejected",
        rejectedBy: req.actorUserId,
        rejectedAt: now,
        rejectionFeedback: req.feedback,
      })
      .where(eq(factoryStages.id, stage.id));

    // Audit
    const auditId = await appendAudit({
      pipelineId: pipeline.id,
      event: "stage_rejected",
      actor: req.actorUserId,
      stageId: req.stageId,
      details: { feedback: req.feedback },
    });

    await FactoryEventTopic.publish({
      project_id: req.id,
      pipeline_id: pipeline.id,
      event_type: "stage_rejected",
      stage_id: req.stageId,
      actor: req.actorUserId,
      details: { feedback: req.feedback },
    });

    return {
      stage: req.stageId,
      rejected_by: req.actorUserId,
      rejected_at: now.toISOString(),
      feedback: req.feedback,
      audit_entry_id: auditId,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-006: Audit Trail
// ---------------------------------------------------------------------------

type AuditRequest = {
  id: string;
  orgId: string;
  from?: string; // ISO date string
  limit?: number;
};

type AuditResponse = {
  entries: AuditEntry[];
  total: number;
};

export const getAudit = api(
  { expose: true, auth: true, method: "GET", path: "/api/projects/:id/factory/audit" },
  async (req: AuditRequest): Promise<AuditResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);
    const limit = Math.min(req.limit ?? 100, 500);

    const conditions = [eq(factoryAuditLog.pipelineId, pipeline.id)];
    if (req.from) {
      const parsed = new Date(req.from);
      if (isNaN(parsed.getTime())) {
        throw APIError.invalidArgument(
          "'from' must be a valid ISO date string"
        );
      }
      conditions.push(gte(factoryAuditLog.timestamp, parsed));
    }

    const entries = await db
      .select()
      .from(factoryAuditLog)
      .where(and(...conditions))
      .orderBy(asc(factoryAuditLog.timestamp))
      .limit(limit);

    // Total count
    const [countRow] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(factoryAuditLog)
      .where(and(...conditions));

    return {
      entries,
      total: countRow.count,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-007: Deployment Handoff
// ---------------------------------------------------------------------------

type DeployRequest = {
  id: string;
  environment: string;
  git_ref: string;
  registry_image?: string;
  actorUserId: string;
  orgId: string;
};

type DeployResponse = {
  deployment_id: string;
  target: string;
  status: string;
};

export const triggerDeploy = api(
  { expose: true, auth: true, method: "POST", path: "/api/projects/:id/factory/deploy" },
  async (req: DeployRequest): Promise<DeployResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    if (pipeline.status !== "completed") {
      throw APIError.failedPrecondition(
        `pipeline status is "${pipeline.status}", must be "completed" to deploy`
      );
    }

    if (!req.environment || !req.git_ref) {
      throw APIError.invalidArgument("environment and git_ref are required");
    }

    let deploymentId: string;
    let deployStatus = "queued";

    // Forward to deployd-api-rs if credentials are configured
    try {
      const { createPreviewDeployment, isDeploydConfigured } = await import(
        "../deploy/deploydClient"
      );

      if (isDeploydConfigured()) {
        const result = await createPreviewDeployment({
          tenant_id: "default",
          app_id: pipeline.projectId,
          env_id: req.environment,
          release_sha: req.git_ref,
          artifact_ref: req.registry_image ?? `ghcr.io/unknown:${req.git_ref}`,
          lane: "LANE_A",
        });
        deploymentId = result.release_id;
        deployStatus = result.status;
      } else {
        // No OIDC credentials configured — local-dev mode
        deploymentId = crypto.randomUUID();
        deployStatus = "queued_local";
      }
    } catch {
      // Graceful degradation: return a local deployment ID
      deploymentId = crypto.randomUUID();
      deployStatus = "queued_local";
    }

    // Audit
    await appendAudit({
      pipelineId: pipeline.id,
      event: "deployment_triggered",
      actor: req.actorUserId,
      details: {
        deployment_id: deploymentId,
        environment: req.environment,
        git_ref: req.git_ref,
        registry_image: req.registry_image,
      },
    });

    await FactoryEventTopic.publish({
      project_id: req.id,
      pipeline_id: pipeline.id,
      event_type: "deployment_triggered",
      actor: req.actorUserId,
      details: { environment: req.environment, deployment_id: deploymentId },
    });

    return {
      deployment_id: deploymentId,
      target: req.environment,
      status: deployStatus,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-009: Pipeline Status Update (lifecycle events from OPC)
// ---------------------------------------------------------------------------

type StatusUpdateRequest = {
  id: string; // project ID (path param)
  pipeline_id: string;
  status: "running" | "paused" | "completed" | "failed";
  current_stage?: string;
  error?: string;
  phase?: "process" | "scaffold";
  actorUserId: string;
  orgId: string;
};

type StatusUpdateResponse = {
  pipeline_id: string;
  status: string;
  audit_entry_id: string;
};

export const updatePipelineStatus = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/status-update",
  },
  async (req: StatusUpdateRequest): Promise<StatusUpdateResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    // Guard: cannot update a terminal pipeline
    if (pipeline.status === "completed" || pipeline.status === "failed") {
      throw APIError.failedPrecondition(
        `pipeline status is "${pipeline.status}" and cannot be updated`
      );
    }

    const now = new Date();
    const isTerminal = req.status === "completed" || req.status === "failed";

    await db
      .update(factoryPipelines)
      .set({
        status: req.status,
        ...(req.status === "running" && !pipeline.startedAt ? { startedAt: now } : {}),
        ...(isTerminal ? { completedAt: now } : {}),
        updatedAt: now,
      })
      .where(eq(factoryPipelines.id, pipeline.id));

    // If a current_stage is provided, mark it as in_progress
    if (req.current_stage) {
      await db
        .update(factoryStages)
        .set({
          status: "in_progress",
          startedAt: now,
        })
        .where(
          and(
            eq(factoryStages.pipelineId, pipeline.id),
            eq(factoryStages.stageId, req.current_stage)
          )
        );
    }

    const auditId = await appendAudit({
      pipelineId: pipeline.id,
      event: "pipeline_status_changed",
      actor: req.actorUserId,
      stageId: req.current_stage,
      details: {
        status: req.status,
        phase: req.phase,
        ...(req.error ? { error: req.error } : {}),
      },
    });

    // Publish events for terminal status changes
    if (req.status === "completed" || req.status === "failed") {
      await FactoryEventTopic.publish({
        project_id: req.id,
        pipeline_id: pipeline.id,
        event_type: req.status === "completed" ? "pipeline_completed" : "pipeline_failed",
        actor: req.actorUserId,
        details: {
          phase: req.phase,
          ...(req.error ? { error: req.error } : {}),
        },
      });
    }

    return {
      pipeline_id: pipeline.id,
      status: req.status,
      audit_entry_id: auditId,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-010: Scaffold Feature Progress (batch upsert from OPC)
// ---------------------------------------------------------------------------

type ScaffoldFeatureReport = {
  feature_id: string;
  category: "data" | "api" | "ui" | "configure" | "trim" | "validate";
  status: "pending" | "in_progress" | "completed" | "failed";
  retry_count?: number;
  last_error?: string;
  files_created?: string[];
  prompt_tokens?: number;
  completion_tokens?: number;
};

type ScaffoldProgressRequest = {
  id: string; // project ID (path param)
  pipeline_id: string;
  features: ScaffoldFeatureReport[];
  actorUserId: string;
  orgId: string;
};

type ScaffoldProgressResponse = {
  upserted: number;
  audit_entry_id: string;
};

export const reportScaffoldProgress = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/scaffold-progress",
  },
  async (req: ScaffoldProgressRequest): Promise<ScaffoldProgressResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    if (!req.features || req.features.length === 0) {
      throw APIError.invalidArgument("features array must not be empty");
    }

    let upserted = 0;
    for (const feat of req.features) {
      // Try to find existing row
      const [existing] = await db
        .select({ id: factoryScaffoldFeatures.id })
        .from(factoryScaffoldFeatures)
        .where(
          and(
            eq(factoryScaffoldFeatures.pipelineId, pipeline.id),
            eq(factoryScaffoldFeatures.featureId, feat.feature_id)
          )
        )
        .limit(1);

      const now = new Date();
      if (existing) {
        await db
          .update(factoryScaffoldFeatures)
          .set({
            status: feat.status,
            ...(feat.retry_count != null ? { retryCount: feat.retry_count } : {}),
            ...(feat.last_error != null ? { lastError: feat.last_error } : {}),
            ...(feat.files_created != null ? { filesCreated: feat.files_created } : {}),
            ...(feat.prompt_tokens != null
              ? { promptTokens: sql`${factoryScaffoldFeatures.promptTokens} + ${feat.prompt_tokens}` }
              : {}),
            ...(feat.completion_tokens != null
              ? { completionTokens: sql`${factoryScaffoldFeatures.completionTokens} + ${feat.completion_tokens}` }
              : {}),
            ...(feat.status === "completed" || feat.status === "failed"
              ? { completedAt: now }
              : {}),
          })
          .where(eq(factoryScaffoldFeatures.id, existing.id));
      } else {
        await db.insert(factoryScaffoldFeatures).values({
          pipelineId: pipeline.id,
          featureId: feat.feature_id,
          category: feat.category,
          status: feat.status,
          retryCount: feat.retry_count ?? 0,
          lastError: feat.last_error ?? null,
          filesCreated: feat.files_created ?? null,
          promptTokens: feat.prompt_tokens ?? 0,
          completionTokens: feat.completion_tokens ?? 0,
          startedAt: now,
          ...(feat.status === "completed" || feat.status === "failed"
            ? { completedAt: now }
            : {}),
        });
      }
      upserted++;
    }

    const auditId = await appendAudit({
      pipelineId: pipeline.id,
      event: "scaffold_progress_reported",
      actor: req.actorUserId,
      details: {
        feature_count: req.features.length,
        completed: req.features.filter((f) => f.status === "completed").length,
        failed: req.features.filter((f) => f.status === "failed").length,
      },
    });

    return {
      upserted,
      audit_entry_id: auditId,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-011: Batch Event Ingestion (orchestrator step events from OPC)
// ---------------------------------------------------------------------------

type OrchestratorEvent = {
  event_type: string;
  step_id?: string;
  timestamp: string;
  payload?: Record<string, unknown>;
};

type EventIngestionRequest = {
  id: string; // project ID (path param)
  pipeline_id: string;
  events: OrchestratorEvent[];
  orgId: string;
};

type EventIngestionResponse = {
  ingested: number;
};

export const ingestEvents = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/events",
  },
  async (req: EventIngestionRequest): Promise<EventIngestionResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    if (!req.events || req.events.length === 0) {
      throw APIError.invalidArgument("events array must not be empty");
    }

    // Cap batch size to prevent abuse
    const events = req.events.slice(0, 200);

    for (const evt of events) {
      await appendAudit({
        pipelineId: pipeline.id,
        event: evt.event_type,
        stageId: evt.step_id,
        details: {
          timestamp: evt.timestamp,
          ...(evt.payload ?? {}),
        },
      });
    }

    return { ingested: events.length };
  }
);

// ---------------------------------------------------------------------------
// FR-008: Pipeline Token Spend Reporting
// ---------------------------------------------------------------------------

type TokenSpendRequest = {
  id: string;
  run_id: string;
  stage_id: string;
  prompt_tokens: number;
  completion_tokens: number;
  model: string;
  orgId: string;
};

export const reportTokenSpend = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/token-spend",
  },
  async (req: TokenSpendRequest): Promise<void> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);

    // Idempotency check: skip if this run_id + stage_id combo was already recorded
    const [existing] = await db
      .select({ id: factoryAuditLog.id })
      .from(factoryAuditLog)
      .where(
        and(
          eq(factoryAuditLog.pipelineId, pipeline.id),
          eq(factoryAuditLog.event, "token_spend_reported"),
          eq(factoryAuditLog.stageId, req.stage_id),
          sql`${factoryAuditLog.details}->>'run_id' = ${req.run_id}`
        )
      )
      .limit(1);

    if (existing) {
      // Already recorded — idempotent no-op
      return;
    }

    // Find stage row
    const stageRows = await db
      .select()
      .from(factoryStages)
      .where(
        and(
          eq(factoryStages.pipelineId, pipeline.id),
          eq(factoryStages.stageId, req.stage_id)
        )
      )
      .limit(1);

    if (stageRows.length === 0) {
      throw APIError.notFound(
        `stage "${req.stage_id}" not found for this pipeline`
      );
    }

    // Accumulate token spend
    await db
      .update(factoryStages)
      .set({
        promptTokens: sql`${factoryStages.promptTokens} + ${req.prompt_tokens}`,
        completionTokens: sql`${factoryStages.completionTokens} + ${req.completion_tokens}`,
        model: req.model,
      })
      .where(eq(factoryStages.id, stageRows[0].id));

    // Audit entry (idempotency key: run_id in details)
    await appendAudit({
      pipelineId: pipeline.id,
      event: "token_spend_reported",
      stageId: req.stage_id,
      details: {
        run_id: req.run_id,
        prompt_tokens: req.prompt_tokens,
        completion_tokens: req.completion_tokens,
        model: req.model,
      },
    });
  }
);

// ---------------------------------------------------------------------------
// FR-012: Pipeline Cancellation
// ---------------------------------------------------------------------------

type CancelRequest = {
  id: string; // project ID (path param)
  reason: string;
  actorUserId: string;
  orgId: string;
};

type CancelResponse = {
  pipeline_id: string;
  cancelled_at: string;
  audit_entry_id: string;
};

export const cancelPipeline = api(
  {
    expose: true,
    auth: true,
    method: "POST",
    path: "/api/projects/:id/factory/cancel",
  },
  async (req: CancelRequest): Promise<CancelResponse> => {
    const pipeline = await getActivePipeline(req.id, req.orgId);
    const now = new Date();

    if (!req.reason) {
      throw APIError.invalidArgument("reason is required for cancellation");
    }

    // Guard: can only cancel active pipelines
    if (
      pipeline.status === "completed" ||
      pipeline.status === "failed" ||
      pipeline.status === "cancelled"
    ) {
      throw APIError.failedPrecondition(
        `pipeline status is "${pipeline.status}" and cannot be cancelled`
      );
    }

    await db
      .update(factoryPipelines)
      .set({
        status: "cancelled",
        completedAt: now,
        updatedAt: now,
      })
      .where(eq(factoryPipelines.id, pipeline.id));

    const auditId = await appendAudit({
      pipelineId: pipeline.id,
      event: "pipeline_cancelled",
      actor: req.actorUserId,
      details: { reason: req.reason },
    });

    await FactoryEventTopic.publish({
      project_id: req.id,
      pipeline_id: pipeline.id,
      event_type: "pipeline_failed", // reuse pipeline_failed for Slack (with cancel context)
      actor: req.actorUserId,
      details: { reason: req.reason, cancelled: true },
    });

    return {
      pipeline_id: pipeline.id,
      cancelled_at: now.toISOString(),
      audit_entry_id: auditId,
    };
  }
);

// ---------------------------------------------------------------------------
// FR-023: Record Stage Artifacts (082 Phase 3)
// ---------------------------------------------------------------------------

type RecordArtifactsRequest = {
  id: string; // project ID (path param)
  pipeline_id: string;
  stage_id: string;
  artifacts: Array<{
    artifact_type: string;
    content_hash: string;
    storage_path: string;
    size_bytes: number;
  }>;
  orgId: string;
};

type RecordArtifactsResponse = {
  recorded: number;
};

export const recordArtifacts = api(
  { expose: true, auth: true, method: "POST", path: "/api/projects/:id/factory/artifacts" },
  async (req: RecordArtifactsRequest): Promise<RecordArtifactsResponse> => {
    await verifyProjectInScope(req.id, req.orgId);

    if (!req.artifacts || req.artifacts.length === 0) {
      return { recorded: 0 };
    }

    const rows = req.artifacts.map((a) => ({
      pipelineId: req.pipeline_id,
      stageId: req.stage_id,
      artifactType: a.artifact_type,
      contentHash: a.content_hash,
      storagePath: a.storage_path,
      sizeBytes: a.size_bytes,
    }));

    await db.insert(factoryArtifacts).values(rows);

    return { recorded: req.artifacts.length };
  }
);

// ---------------------------------------------------------------------------
// FR-025: Lookup Artifacts from Previous Runs (082 Phase 3)
// ---------------------------------------------------------------------------

type LookupArtifactsRequest = {
  id: string; // project ID (path param)
  content_hash: string;
  stage_id: string;
  orgId: string;
};

type LookupArtifactsResponse = {
  found: boolean;
  artifact: {
    pipeline_id: string;
    stage_id: string;
    artifact_type: string;
    content_hash: string;
    storage_path: string;
    size_bytes: number;
    created_at: string;
  } | null;
};

export const lookupArtifact = api(
  { expose: true, auth: true, method: "GET", path: "/api/projects/:id/factory/artifacts/lookup" },
  async (req: LookupArtifactsRequest): Promise<LookupArtifactsResponse> => {
    await verifyProjectInScope(req.id, req.orgId);

    const rows = await db
      .select()
      .from(factoryArtifacts)
      .innerJoin(
        factoryPipelines,
        eq(factoryArtifacts.pipelineId, factoryPipelines.id)
      )
      .where(
        and(
          eq(factoryPipelines.projectId, req.id),
          eq(factoryArtifacts.contentHash, req.content_hash),
          eq(factoryArtifacts.stageId, req.stage_id),
          eq(factoryPipelines.status, "completed")
        )
      )
      .orderBy(desc(factoryArtifacts.createdAt))
      .limit(1);

    if (rows.length === 0) {
      return { found: false, artifact: null };
    }

    const a = rows[0].factory_artifacts;
    return {
      found: true,
      artifact: {
        pipeline_id: a.pipelineId,
        stage_id: a.stageId,
        artifact_type: a.artifactType,
        content_hash: a.contentHash,
        storage_path: a.storagePath,
        size_bytes: a.sizeBytes,
        created_at: a.createdAt.toISOString(),
      },
    };
  }
);

// ---------------------------------------------------------------------------
// Project-scoped artifact recording (spec 094 Slice 5; renamed from
// workspace-scoped by spec 119 Phase C)
// ---------------------------------------------------------------------------

type ProjectRecordArtifactRequest = {
  projectId: string; // path param
  content_hash: string;
  filename: string;
  step_id: string;
  workflow_id: string;
  size_bytes: number;
  content_type?: string;
  producer_agent?: string;
};

type ProjectRecordArtifactResponse = {
  recorded: boolean;
};

export const projectRecordArtifact = api(
  { expose: true, auth: true, method: "POST", path: "/api/projects/:projectId/artifacts" },
  async (req: ProjectRecordArtifactRequest): Promise<ProjectRecordArtifactResponse> => {
    await db.insert(factoryArtifacts).values({
      pipelineId: req.workflow_id, // reuse pipelineId for workflow_id
      stageId: req.step_id,
      artifactType: req.content_type ?? "application/octet-stream",
      contentHash: req.content_hash,
      storagePath: req.filename,
      sizeBytes: req.size_bytes,
      projectId: req.projectId,
      producerAgent: req.producer_agent ?? null,
    });

    return { recorded: true };
  }
);

type ProjectLookupArtifactRequest = {
  projectId: string; // path param
  content_hash: string;
};

type ProjectLookupArtifactResponse = {
  found: boolean;
  artifacts: Array<{
    workflow_id: string;
    step_id: string;
    filename: string;
    content_hash: string;
    size_bytes: number;
    producer_agent: string | null;
    created_at: string;
  }>;
};

export const projectLookupArtifact = api(
  { expose: true, auth: true, method: "GET", path: "/api/projects/:projectId/artifacts" },
  async (req: ProjectLookupArtifactRequest): Promise<ProjectLookupArtifactResponse> => {
    const rows = await db
      .select()
      .from(factoryArtifacts)
      .where(
        and(
          eq(factoryArtifacts.projectId, req.projectId),
          eq(factoryArtifacts.contentHash, req.content_hash)
        )
      )
      .orderBy(desc(factoryArtifacts.createdAt))
      .limit(10);

    return {
      found: rows.length > 0,
      artifacts: rows.map((a) => ({
        workflow_id: a.pipelineId,
        step_id: a.stageId,
        filename: a.storagePath,
        content_hash: a.contentHash,
        size_bytes: a.sizeBytes,
        producer_agent: a.producerAgent,
        created_at: a.createdAt.toISOString(),
      })),
    };
  }
);

// ---------------------------------------------------------------------------
// Promotion API (spec 097 — Promotion-Grade Platform Mirror)
// ---------------------------------------------------------------------------

interface PromotionRequest {
  projectId: string;
  workflowId: string;
  pipelineId: string;
  promotedBy?: string;
}

interface PromotionResult {
  eligible: boolean;
  promotionId?: string;
  missingRecords: string[];
}

/**
 * Validate a completed pipeline run for promotion eligibility.
 *
 * Checks that the pipeline belongs to the project, all stages have records,
 * artifacts are present, and the audit log has a completion event. If all
 * checks pass, creates a promotion record. Spec 097 Slice 3 (renamed from
 * workspace-scoped to project-scoped by spec 119 Phase C).
 */
export const createPromotion = api(
  { expose: true, auth: true, method: "POST", path: "/api/projects/:projectId/promotions" },
  async (req: PromotionRequest): Promise<PromotionResult> => {
    const missingRecords: string[] = [];

    // 1. Check pipeline exists and belongs to project
    const [pipeline] = await db
      .select()
      .from(factoryPipelines)
      .where(eq(factoryPipelines.id, req.pipelineId))
      .limit(1);

    if (!pipeline) {
      throw APIError.notFound(`Pipeline ${req.pipelineId} not found`);
    }

    if (pipeline.projectId !== req.projectId) {
      throw APIError.permissionDenied("Pipeline does not belong to this project");
    }

    // 2. Check all expected stages have records
    const stages = await db
      .select()
      .from(factoryStages)
      .where(eq(factoryStages.pipelineId, req.pipelineId));

    const completedStages = stages.filter(
      (s) => s.status === "completed" || s.status === "confirmed"
    );
    if (completedStages.length < PIPELINE_STAGES.length) {
      missingRecords.push(
        `stages: ${completedStages.length}/${PIPELINE_STAGES.length} completed`
      );
    }

    // 3. Check artifacts exist for this pipeline
    const artifacts = await db
      .select()
      .from(factoryArtifacts)
      .where(eq(factoryArtifacts.pipelineId, req.pipelineId));

    if (artifacts.length === 0) {
      missingRecords.push("no artifacts recorded for pipeline");
    }

    // 4. Check audit log has completion event
    const completionEvents = await db
      .select()
      .from(factoryAuditLog)
      .where(
        and(
          eq(factoryAuditLog.pipelineId, req.pipelineId),
          eq(factoryAuditLog.event, "pipeline_completed")
        )
      )
      .limit(1);

    if (completionEvents.length === 0) {
      missingRecords.push("no pipeline_completed event in audit log");
    }

    // 5. Check pipeline status is completed
    if (pipeline.status !== "completed") {
      missingRecords.push(`pipeline status is '${pipeline.status}', expected 'completed'`);
    }

    if (missingRecords.length > 0) {
      return { eligible: false, missingRecords };
    }

    // All checks passed — create promotion record
    const [promotion] = await db
      .insert(promotions)
      .values({
        projectId: req.projectId,
        pipelineId: req.pipelineId,
        workflowId: req.workflowId,
        promotedBy: req.promotedBy ?? null,
        evidence: {
          stageCount: stages.length,
          artifactCount: artifacts.length,
          completedAt: pipeline.completedAt?.toISOString(),
        },
      })
      .returning({ id: promotions.id });

    return {
      eligible: true,
      promotionId: promotion.id,
      missingRecords: [],
    };
  }
);
