{{- if and .Values.secretsMount.enabled (eq (default "k8s" .Values.secrets.provider) "csi-azure") }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: deployd-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
{{- range .Values.secretsMount.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          {{- if .objectAlias }}
          objectAlias: {{ .objectAlias }}
          {{- end }}
{{- end }}
{{- end }}
